import asyncio
import base64
import datetime
import json
import os
import shutil
import sys
from typing import Union, List, Optional
import re
import ssl
from pathlib import Path

import aiohttp
import certifi
import click
from rich.console import Console
from rich.table import Table

from hidemyemail_generator.hidemyemail import HideMyEmail
from hidemyemail_generator.inbox import (
    ADDRESS_STATES,
    DEFAULT_DB_FILE,
    DEFAULT_FOLDER,
    DEFAULT_INBOX_CONFIG_FILE,
    InboxConfig,
    connect_db,
    count_addresses_since,
    count_unread,
    create_batch,
    export_csv_files,
    get_batch,
    list_addresses,
    list_batches,
    list_messages,
    load_config,
    mark_address,
    mark_messages_read,
    mask_account,
    save_config,
    set_address_metadata,
    set_batch_state,
    sync_inbox,
    upsert_address,
)


MAX_CONCURRENT_TASKS = 10
# Apple allows roughly five new addresses per 30 minutes per family member.
# The window is not exposed by any API, so headroom is an estimate derived
# from what the local database has seen.
RATE_LIMIT_WINDOW_SECONDS = 30 * 60
RATE_LIMIT_PER_WINDOW = 5
DEFAULT_COOKIE_FILENAME = "cookies.txt"
DEFAULT_EMAIL_FILENAME = "emails.txt"
DEFAULT_HME_NOTE = "Generated by rtuna's iCloud email generator"
DEFAULT_REGION = os.environ.get("HIDEMYEMAIL_REGION", "global").lower()
REGION_CHOICE = click.Choice(["global", "china"], case_sensitive=False)
SETUP_VALIDATE_URLS = {
    "global": "https://setup.icloud.com/setup/ws/1/validate",
    "china": "https://setup.icloud.com.cn/setup/ws/1/validate",
}
COOKIE_CAPTURE_URLS = {
    "global": "https://www.icloud.com/icloudplus/",
    "china": "https://www.icloud.com.cn/icloudplus/",
}
HIDEMYEMAIL_APP_PATH = "/applications/hidemyemail/current/"


def maildomain_suffix(region: str) -> str:
    return "com.cn" if region == "china" else "com"


def bridge_error(response: dict | None) -> dict:
    if not response:
        return {"code": None, "message": "Empty response from iCloud", "retry_after": None}

    error = response.get("error")
    if isinstance(error, dict):
        code = error.get("errorCode")
        if code is None:
            code = error.get("code")
        message = (
            error.get("errorMessage")
            or error.get("message")
            or response.get("reason")
            or "Unknown error"
        )
        retry_after = error.get("retryAfter")
    else:
        code = error if isinstance(error, int) else None
        message = response.get("reason") or str(error or "Unknown error")
        retry_after = response.get("retryAfter")

    return {
        "code": str(code) if code is not None else None,
        "message": str(message),
        "retry_after": retry_after if isinstance(retry_after, (int, float)) else None,
    }


def write_result_json(result_file: str | None, payload: dict) -> None:
    if result_file:
        path = Path(result_file)
        path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
        path.chmod(0o600)


def account_summary(account: dict) -> dict:
    ds_info = account.get("dsInfo", {})
    full_name = ds_info.get("fullName") or " ".join(
        part for part in [ds_info.get("firstName"), ds_info.get("lastName")] if part
    )
    maildomain = account.get("webservices", {}).get("maildomainws", {})
    maildomain_host = (
        account.get("detectedMaildomainHost") or maildomain.get("url") or ""
    )
    maildomain_host = re.sub(r"^https?://", "", maildomain_host).split("/", 1)[0]
    user_partition = account.get("userPartition")
    try:
        user_partition = int(user_partition) if user_partition is not None else None
    except (TypeError, ValueError):
        user_partition = None

    return {
        "apple_id": ds_info.get("appleId") or "Unknown",
        "name": full_name or "Unknown",
        "dsid": str(ds_info.get("dsid")) if ds_info.get("dsid") is not None else None,
        "user_partition": user_partition,
        "maildomain_host": maildomain_host,
        "hide_my_email_available": bool(
            ds_info.get("isHideMyEmailFeatureAvailable")
        ),
    }


def load_cookie_context(cookie_file: str, region: str) -> tuple[str, str]:
    with open(cookie_file, "r") as f:
        content = "\n".join(
            line.strip() for line in f if not line.lstrip().startswith("//")
        ).strip()
    normalized_content = (
        content.replace('^"', '"')
        .replace("^'", "'")
        .replace("^\n", "")
        .replace("^\r\n", "")
    )

    maildomain_host = ""
    explicit_maildomain_host = re.search(
        r"(?m)^HIDEMYEMAIL_MAILDOMAIN_HOST=([A-Za-z0-9.-]+)\s*$",
        normalized_content,
    )
    if explicit_maildomain_host:
        maildomain_host = explicit_maildomain_host.group(1).strip()

    encoded_cookie = re.search(
        r"(?m)^HIDEMYEMAIL_COOKIE_BASE64=([A-Za-z0-9+/=]+)\s*$",
        normalized_content,
    )
    if encoded_cookie:
        cookie = base64.b64decode(encoded_cookie.group(1)).decode("utf-8")
        return cookie.strip(), maildomain_host

    shard = re.search(
        r"https://(p\d+)-[^/\s'\"]+\.icloud\.com(?:\.cn)?", normalized_content
    )
    if shard:
        maildomain_host = (
            f"{shard.group(1)}-maildomainws.icloud.{maildomain_suffix(region)}"
        )

    cmd_cookie_arg = re.search(
        r"(?:^|\s)(?:-b|--cookie)\s+\^\"(.+?)\^\"\s+\^?\s*-[A-Za-z]",
        content,
        re.IGNORECASE | re.DOTALL,
    )
    if cmd_cookie_arg:
        cookie = (
            cmd_cookie_arg.group(1)
            .replace('^\\^"', '"')
            .replace('\\"', '"')
            .replace('^"', '"')
            .replace("\r", "")
            .replace("\n", "")
        )
        return cookie.strip(), maildomain_host

    cookie_arg = re.search(
        r"(?:^|\s)(?:-b|--cookie)\s+\"([^\"]+)\"",
        normalized_content,
        re.IGNORECASE,
    )
    if cookie_arg:
        return cookie_arg.group(1).strip(), maildomain_host

    cookie_header = re.search(
        r"cookie\s*:\s*([^'\"\r\n]+)", normalized_content, re.IGNORECASE
    )
    if cookie_header:
        return cookie_header.group(1).strip(), maildomain_host

    lines = normalized_content.splitlines()
    return (lines[0].strip() if lines else ""), maildomain_host


async def fetch_account_info(cookie_file: str, region: str) -> dict:
    cookie, maildomain_host = load_cookie_context(cookie_file, region)
    if not cookie:
        return {"error": "Cookie file is empty"}

    return await fetch_account_info_from_cookie(cookie, region, maildomain_host)


async def fetch_account_info_from_cookie(
    cookie: str, region: str, maildomain_host: str = ""
) -> dict:
    headers = HideMyEmail.browser_headers(region, cookie)
    connector = aiohttp.TCPConnector(
        ssl_context=ssl.create_default_context(cafile=certifi.where())
    )

    async with aiohttp.ClientSession(
        headers=headers,
        timeout=aiohttp.ClientTimeout(total=30),
        connector=connector,
    ) as session:
        async with session.get(SETUP_VALIDATE_URLS[region]) as response:
            try:
                data = await response.json(content_type=None)
            except Exception:
                return {"error": f"Unexpected response from iCloud ({response.status})"}

    if response.status != 200:
        reason = data.get("reason") or data.get("error") or response.status
        return {"error": f"Failed to validate cookie: {reason}"}

    user_partition = data.get("userPartition")
    if not maildomain_host and user_partition:
        maildomain_host = (
            f"p{user_partition}-maildomainws.icloud.{maildomain_suffix(region)}"
        )

    data["detectedMaildomainHost"] = maildomain_host
    return data


def write_captured_cookie(
    cookie_file: str, cookie: str, region: str, request_url: str, maildomain_host: str
) -> None:
    path = Path(cookie_file)
    if path.exists() and path.stat().st_size > 0:
        shutil.copy2(path, path.with_name(f"{path.name}.bak"))

    encoded_cookie = base64.b64encode(cookie.encode("utf-8")).decode("ascii")
    path.write_text(
        "\n".join(
            [
                "# Generated by hidemyemail capture-cookie.",
                f"HIDEMYEMAIL_REGION={region}",
                f"HIDEMYEMAIL_REQUEST_URL={request_url}",
                f"HIDEMYEMAIL_MAILDOMAIN_HOST={maildomain_host}",
                f"HIDEMYEMAIL_COOKIE_BASE64={encoded_cookie}",
                "",
            ]
        ),
        encoding="utf-8",
    )


class RichHideMyEmail(HideMyEmail):
    def __init__(
        self,
        cookie_file: str,
        output_file: str = "",
        no_output_file: bool = False,
        region: str = DEFAULT_REGION,
    ):
        cookies = ""
        maildomain_host = ""
        if os.path.exists(cookie_file):
            cookies, maildomain_host = load_cookie_context(cookie_file, region)

        super().__init__(cookies=cookies, region=region, maildomain_host=maildomain_host)
        self.console = Console()
        self.table = Table()
        self._output_file = output_file
        self._no_output_file = no_output_file
        self.last_error = None

        if not os.path.exists(cookie_file):
            self.console.log(
                f'[bold yellow][WARN][/] No "{cookie_file}" file found! 未找到 Cookie 文件，可能无法授权访问。'
            )
        elif "X-APPLE-WEBAUTH-USER" not in self.cookies:
            self.console.log(
                "[bold yellow][WARN][/] Cookie is missing X-APPLE-WEBAUTH-USER. Cookie 缺少授权字段；请复制已登录的 iCloud 请求，优先 maildomainws 或 hme，不要用 feedbackws/reportStats。"
            )

    def _check_response(
        self, response: dict, action: str, email: Optional[str] = None
    ) -> bool:
        if not response:
            self.last_error = bridge_error(response)
            return False
        if "success" not in response or not response["success"]:
            self.last_error = bridge_error(response)
            email_prefix = f' "{email}"' if email else ""
            self.console.log(
                f"[bold red][ERR][/]{email_prefix} - Failed to {action}. 失败原因: {self.last_error['message']}"
            )
            return False
        return True

    async def _generate_one(self, label: str) -> Union[str, None]:
        # First, generate an email
        gen_res = await self.generate_email()

        if not self._check_response(gen_res, "generate email"):
            return

        email = gen_res["result"]["hme"]
        self.console.log(f'[50%] "{email}" - Successfully generated / 生成成功')

        # Then, reserve it
        reserve_res = await self.reserve_email(email, label, DEFAULT_HME_NOTE)

        if not self._check_response(reserve_res, "reserve email", email):
            return

        self.console.log(f'[100%] "{email}" - Successfully reserved / 保留成功')
        return email

    async def _generate(self, label: str, num: int):
        tasks = []
        for _ in range(num):
            task = asyncio.ensure_future(self._generate_one(label))
            tasks.append(task)

        return filter(lambda e: e is not None, await asyncio.gather(*tasks))

    async def generate(self, label: str, count: int) -> List[str]:
        try:
            self.last_error = None
            emails = []
            self.console.rule()
            if count < 1:
                self.last_error = {
                    "code": None,
                    "message": "Count should be >= 1",
                    "retry_after": None,
                }
                self.console.log("Count should be >= 1 / 数量必须大于等于 1")
                return emails
            self.console.log(f"Generating {count} email(s)... / 正在生成 {count} 个邮箱...")
            self.console.rule()

            with self.console.status("[bold green]Generating iCloud email(s)..."):
                while count > 0:
                    batch = await self._generate(
                        label,
                        count if count < MAX_CONCURRENT_TASKS else MAX_CONCURRENT_TASKS,
                    )
                    count -= MAX_CONCURRENT_TASKS
                    emails += batch

            if len(emails) > 0:
                if not self._no_output_file:
                    with open(self._output_file, "a+") as f:
                        f.write(os.linesep.join(emails) + os.linesep)

                    self.console.rule()
                    self.console.log(
                        f':star: Emails have been saved into "{self._output_file}" / 邮箱已保存'
                    )
                else:
                    self.console.rule()

                self.console.log(
                    f"[bold green]All done![/] Successfully generated [bold green]{len(emails)}[/] email(s) / 已生成 [bold green]{len(emails)}[/] 个邮箱"
                )

            return emails
        except KeyboardInterrupt:
            return []

    async def list(self, label_query: Optional[str], active: bool) -> dict:
        gen_res = await self.list_email()
        if not self._check_response(gen_res, "list emails"):
            return {"ok": False, "addresses": [], "error": self.last_error}

        self.table.add_column("Label / 标签")
        self.table.add_column("Hide My Email / 隐藏邮箱")
        self.table.add_column("Created At / 创建时间")
        self.table.add_column("Is Active / 使用中")

        addresses = []
        for row in gen_res["result"]["hmeEmails"]:
            if row["isActive"] == active and (
                label_query is None or re.search(label_query, row["label"])
            ):
                created_at = datetime.datetime.fromtimestamp(
                    row["createTimestamp"] / 1000, tz=datetime.timezone.utc
                ).isoformat()
                addresses.append(
                    {
                        "email": row["hme"],
                        "label": row["label"],
                        "created_at": created_at,
                        "is_active": bool(row["isActive"]),
                        "anonymous_id": row.get("anonymousId") or "",
                    }
                )
                self.table.add_row(
                    row["label"],
                    row["hme"],
                    str(datetime.datetime.fromtimestamp(row["createTimestamp"] / 1000)),
                    str(row["isActive"]),
                )

        self.console.print(self.table)
        return {"ok": True, "addresses": addresses, "error": None}

    async def _resolve(self, email: str) -> Optional[dict]:
        """Looks up the iCloud record for an address, needed for its anonymousId."""
        gen_res = await self.list_email()
        if not self._check_response(gen_res, "list emails"):
            return None

        for row in gen_res["result"]["hmeEmails"]:
            if row.get("hme") != email:
                continue
            if not row.get("anonymousId"):
                self.last_error = {
                    "code": None,
                    "message": f'iCloud returned no identifier for "{email}"',
                    "retry_after": None,
                }
                self.console.log(f"[bold red][ERR][/] {self.last_error['message']}")
                return None
            return row

        self.last_error = {
            "code": None,
            "message": f'No Hide My Email address matching "{email}"',
            "retry_after": None,
        }
        self.console.log(
            f'[bold red][ERR][/] {self.last_error["message"]} / 未找到匹配的隐藏邮箱'
        )
        return None

    async def set_active(self, email: str, active: bool) -> dict:
        self.last_error = None
        row = await self._resolve(email)
        if row is None:
            return {"ok": False, "email": email, "is_active": None, "error": self.last_error}

        action = "reactivate" if active else "deactivate"
        call = self.reactivate_email if active else self.deactivate_email
        res = await call(row["anonymousId"])
        if not self._check_response(res, f"{action} email", email):
            return {"ok": False, "email": email, "is_active": None, "error": self.last_error}

        self.console.log(
            f'[bold green][OK][/] "{email}" - Successfully {action}d / 操作成功'
        )
        return {"ok": True, "email": email, "is_active": active, "error": None}

    async def update_metadata(
        self, email: str, label: Optional[str], note: Optional[str]
    ) -> dict:
        self.last_error = None
        row = await self._resolve(email)
        if row is None:
            return {
                "ok": False,
                "email": email,
                "label": None,
                "note": None,
                "error": self.last_error,
            }

        new_label = label if label is not None else row.get("label") or ""
        new_note = note if note is not None else row.get("note") or ""
        res = await self.update_email_metadata(row["anonymousId"], new_label, new_note)
        if not self._check_response(res, "update email metadata", email):
            return {
                "ok": False,
                "email": email,
                "label": None,
                "note": None,
                "error": self.last_error,
            }

        self.console.log(f'[bold green][OK][/] "{email}" - Metadata updated / 已更新')
        return {
            "ok": True,
            "email": email,
            "label": new_label,
            "note": new_note,
            "error": None,
        }


@click.group()
def cli():
    pass


@click.command()
@click.option("--count", default=1, help="How many emails to generate / 生成数量", type=int)
@click.option(
    "--label",
    required=True,
    help="Label to set for generated emails / 生成邮箱的标签",
)
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--output",
    default=DEFAULT_EMAIL_FILENAME,
    help="Path to output file for saving emails / 邮箱输出文件路径",
    type=click.Path(),
)
@click.option(
    "--no-output-file",
    is_flag=True,
    default=False,
    help="Do not save emails to an output file / 不保存到输出文件",
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    help="Local inbox database file / 本地收件台数据库",
    type=click.Path(),
)
@click.option(
    "--no-db",
    is_flag=True,
    default=False,
    help="Do not save generated addresses to the local inbox database / 不写入本地数据库",
)
@click.option(
    "--batch-id",
    help="Attribute the addresses to this batch / 归入此批次",
)
@click.option(
    "--result-json",
    type=click.Path(dir_okay=False),
    help="Write a machine-readable result to this file",
)
def generatecommand(
    count: int,
    label: str,
    cookie_file: str,
    output: str,
    no_output_file: bool,
    region: str,
    db_file: str,
    no_db: bool,
    batch_id: Optional[str],
    result_json: Optional[str],
):
    "Generate emails / 生成隐藏邮箱"
    try:
        result = asyncio.run(
            _generate(
                label,
                count,
                cookie_file,
                output,
                no_output_file,
                region,
                db_file,
                no_db,
                batch_id,
            )
        )
    except KeyboardInterrupt:
        return

    write_result_json(result_json, result)
    if result_json and not result["ok"]:
        raise click.ClickException(result["error"]["message"])


@click.command()
@click.option(
    "--label-query",
    help='Query to search within the "Label" field / 按标签搜索',
)
@click.option(
    "--active/--inactive", default=True, help="Filter Active / Inactive emails / 筛选使用中或已停用地址"
)
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def listcommand(
    label_query: Optional[str],
    active: bool,
    cookie_file: str,
    region: str,
    result_json: Optional[str],
):
    "List emails / 查看隐藏邮箱"
    try:
        result = asyncio.run(_list(label_query, active, cookie_file, region))
    except KeyboardInterrupt:
        return
    write_result_json(result_json, result)
    if result_json and not result["ok"]:
        raise click.ClickException(result["error"]["message"])


@click.command()
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option(
    "--result-json",
    type=click.Path(dir_okay=False),
    help="Write a machine-readable result to this file",
)
def whoamicommand(cookie_file: str, region: str, result_json: Optional[str]):
    "Show the account represented by the saved cookie / 查看当前 Cookie 对应账号"
    try:
        result = asyncio.run(_whoami(cookie_file, region))
    except KeyboardInterrupt:
        return

    write_result_json(result_json, result)
    if not result["ok"]:
        raise click.ClickException("Could not identify the saved iCloud cookie")


@click.command()
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
def capturecookiecommand(cookie_file: str, region: str):
    "Open iCloud Plus and capture the Hide My Email request cookie / 自动捕获 iCloud Cookie"
    try:
        ok = asyncio.run(_capture_cookie(cookie_file, region))
    except KeyboardInterrupt:
        return

    if not ok:
        raise click.ClickException("Could not capture the iCloud cookie")


@click.command()
@click.argument("email")
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
    help="Local database to mirror the change into / 同步到本地数据库",
)
@click.option(
    "--result-json",
    type=click.Path(dir_okay=False),
    help="Write a machine-readable result to this file",
)
def deactivatecommand(
    email: str, cookie_file: str, region: str, db_file: str, result_json: Optional[str]
):
    "Stop an address from forwarding mail / 停用隐藏邮箱转发"
    _run_address_command(
        _set_active(email, False, cookie_file, region), result_json, db_file
    )


@click.command()
@click.argument("email")
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
    help="Local database to mirror the change into / 同步到本地数据库",
)
@click.option(
    "--result-json",
    type=click.Path(dir_okay=False),
    help="Write a machine-readable result to this file",
)
def reactivatecommand(
    email: str, cookie_file: str, region: str, db_file: str, result_json: Optional[str]
):
    "Resume forwarding for a deactivated address / 恢复已停用的隐藏邮箱"
    _run_address_command(
        _set_active(email, True, cookie_file, region), result_json, db_file
    )


@click.command()
@click.argument("email")
@click.option("--label", help="New label / 新标签")
@click.option("--note", help="New note / 新备注")
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file / Cookie 文件路径",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
    help="Local database to mirror the change into / 同步到本地数据库",
)
@click.option(
    "--result-json",
    type=click.Path(dir_okay=False),
    help="Write a machine-readable result to this file",
)
def updatemetadatacommand(
    email: str,
    label: Optional[str],
    note: Optional[str],
    cookie_file: str,
    region: str,
    db_file: str,
    result_json: Optional[str],
):
    "Change the label or note of an address / 修改隐藏邮箱的标签或备注"
    if label is None and note is None:
        raise click.UsageError("Provide --label and/or --note / 请提供 --label 或 --note")
    _run_address_command(
        _update_metadata(email, label, note, cookie_file, region), result_json, db_file
    )


@click.group(name="inbox")
def inboxgroup():
    "Local inbox, verification code, and address state management / 本地收件台、验证码和地址状态管理"
    pass


@inboxgroup.command(name="setup")
@click.option("--host", help="IMAP host, for example imap.gmail.com / IMAP 主机")
@click.option("--port", default=993, show_default=True, type=int, help="IMAP port / IMAP 端口")
@click.option("--username", help="IMAP username / IMAP 用户名")
@click.option("--password", help="IMAP password or app password / IMAP 密码或应用专用密码")
@click.option("--folder", default=DEFAULT_FOLDER, show_default=True, help="IMAP folder / IMAP 文件夹")
@click.option("--ssl/--no-ssl", "use_ssl", default=True, show_default=True)
@click.option(
    "--config-file",
    default=DEFAULT_INBOX_CONFIG_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
def inbox_setup(
    host: Optional[str],
    port: int,
    username: Optional[str],
    password: Optional[str],
    folder: str,
    use_ssl: bool,
    config_file: str,
    db_file: str,
):
    "Configure the local IMAP inbox / 配置本地 IMAP 收件台"
    host = host or click.prompt("IMAP host / IMAP 主机")
    username = username or click.prompt("IMAP username / IMAP 用户名")
    password = password or click.prompt("IMAP password/app password / IMAP 密码或应用专用密码", hide_input=True)
    config = InboxConfig(
        host=host,
        port=port,
        username=username,
        password=password,
        folder=folder,
        use_ssl=use_ssl,
    )
    save_config(config, config_file)
    connect_db(db_file).close()
    console = Console()
    console.log(f'[bold green][OK][/] Saved inbox config to "{config_file}" / 已保存收件台配置')
    console.log(f"[dim]Account / 账号: {mask_account(username)} | Folder / 文件夹: {folder}[/]")


@inboxgroup.command(name="status")
@click.option(
    "--config-file",
    default=DEFAULT_INBOX_CONFIG_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_status(config_file: str, db_file: str, result_json: Optional[str]):
    "Show local inbox configuration and database counts / 查看本地收件台状态"
    console = Console()
    try:
        config = load_config(config_file)
    except Exception as e:
        write_result_json(
            result_json,
            {
                "ok": False,
                "config": None,
                "counts": None,
                "error": bridge_error({"reason": str(e)}),
            },
        )
        raise click.ClickException(str(e)) from e

    conn = connect_db(db_file)
    try:
        state_counts = {state: 0 for state in ADDRESS_STATES}
        state_counts.update(
            {
                row["state"]: row["count"]
                for row in conn.execute(
                    "SELECT state, COUNT(*) AS count FROM addresses GROUP BY state"
                ).fetchall()
            }
        )
        counts = {
            "addresses": conn.execute("SELECT COUNT(*) FROM addresses").fetchone()[0],
            "messages": conn.execute("SELECT COUNT(*) FROM messages").fetchone()[0],
            "codes": conn.execute(
                "SELECT COUNT(*) FROM messages WHERE code IS NOT NULL AND code != ''"
            ).fetchone()[0],
            "unread": count_unread(conn),
            "deactivated": conn.execute(
                "SELECT COUNT(*) FROM addresses WHERE is_active = 0"
            ).fetchone()[0],
            "states": state_counts,
        }
    finally:
        conn.close()

    table = Table(title="Local Inbox / 本地收件台")
    table.add_column("Field / 字段")
    table.add_column("Value / 值")
    table.add_row("IMAP host / IMAP 主机", f"{config.host}:{config.port}")
    table.add_row("Account / 账号", mask_account(config.username))
    table.add_row("Folder / 文件夹", config.folder)
    table.add_row("SSL", str(config.use_ssl))
    table.add_row("Addresses / 地址", str(counts["addresses"]))
    table.add_row("Deactivated / 已停用", str(counts["deactivated"]))
    table.add_row("Messages / 邮件", str(counts["messages"]))
    table.add_row("Unread / 未读", str(counts["unread"]))
    table.add_row("Codes / 验证码", str(counts["codes"]))
    console.print(table)
    write_result_json(
        result_json,
        {
            "ok": True,
            "config": {
                "host": config.host,
                "port": config.port,
                "username": mask_account(config.username),
                "folder": config.folder,
                "use_ssl": config.use_ssl,
            },
            "counts": counts,
            "error": None,
        },
    )


@inboxgroup.command(name="sync")
@click.option(
    "--config-file",
    default=DEFAULT_INBOX_CONFIG_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--limit", default=50, show_default=True, type=int)
@click.option("--show-codes", is_flag=True, default=False)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_sync(
    config_file: str,
    db_file: str,
    limit: int,
    show_codes: bool,
    result_json: Optional[str],
):
    "Fetch new inbox messages through IMAP / 通过 IMAP 同步新邮件"
    console = Console()
    try:
        config = load_config(config_file)
        inserted = sync_inbox(config, db_file=db_file, limit=limit)
    except Exception as e:
        write_result_json(
            result_json,
            {
                "ok": False,
                "count": 0,
                "messages": [],
                "error": bridge_error({"reason": str(e)}),
            },
        )
        raise click.ClickException(str(e)) from e

    console.log(f"[bold green][OK][/] Synced {len(inserted)} new message(s) / 已同步 {len(inserted)} 封新邮件")
    if inserted:
        table = Table(title="New Messages / 新邮件")
        table.add_column("Received / 收件时间")
        table.add_column("HME / 隐藏邮箱")
        table.add_column("Subject / 标题")
        table.add_column("Code / 验证码")
        for row in inserted[:20]:
            table.add_row(
                row.get("received_at") or "",
                row.get("hme_address") or "",
                row.get("subject") or "",
                row.get("code") or "",
            )
        console.print(table)

    if show_codes:
        _print_messages(db_file, only_codes=True, limit=20)
    write_result_json(
        result_json,
        {
            "ok": True,
            "count": len(inserted),
            "messages": [_message_payload(row) for row in inserted],
            "error": None,
        },
    )


@inboxgroup.command(name="codes")
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--limit", default=20, show_default=True, type=int)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_codes(db_file: str, limit: int, result_json: Optional[str]):
    "Show recent messages with verification codes / 查看最近验证码邮件"
    try:
        rows = _print_messages(db_file, only_codes=True, limit=limit)
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "messages": [], "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e
    write_result_json(
        result_json,
        {"ok": True, "messages": rows, "error": None},
    )


@inboxgroup.command(name="messages")
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--limit", default=20, show_default=True, type=int)
@click.option(
    "--unread",
    is_flag=True,
    default=False,
    help="Only show unread messages / 仅显示未读邮件",
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_messages(db_file: str, limit: int, unread: bool, result_json: Optional[str]):
    "Show recent inbox messages / 查看最近收件"
    try:
        rows = _print_messages(
            db_file, only_codes=False, limit=limit, only_unread=unread
        )
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "messages": [], "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e
    write_result_json(
        result_json,
        {"ok": True, "messages": rows, "error": None},
    )


@inboxgroup.command(name="addresses")
@click.option(
    "--state",
    type=click.Choice(ADDRESS_STATES),
    help="Filter by local address state / 按本地地址状态筛选",
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--limit", default=50, show_default=True, type=int)
@click.option(
    "--active/--inactive",
    "active",
    default=None,
    help="Filter by iCloud forwarding state / 按 iCloud 转发状态筛选",
)
@click.option("--query", help="Search email and label / 搜索邮箱和标签")
@click.option("--batch-id", help="Only addresses from this batch / 仅显示此批次的地址")
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_addresses(
    state: Optional[str],
    db_file: str,
    limit: int,
    active: Optional[bool],
    query: Optional[str],
    batch_id: Optional[str],
    result_json: Optional[str],
):
    "List local Hide My Email addresses / 查看本地隐藏邮箱地址"
    try:
        conn = connect_db(db_file)
        try:
            rows = list_addresses(
                conn,
                state=state,
                limit=limit,
                active=active,
                query=query,
                batch_id=batch_id,
            )
        finally:
            conn.close()
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "addresses": [], "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e

    addresses = [_address_payload(row) for row in rows]
    table = Table(title="Local Addresses / 本地地址")
    table.add_column("Email / 邮箱")
    table.add_column("Label / 标签")
    table.add_column("State / 状态")
    table.add_column("Forwarding / 转发")
    table.add_column("Source / 来源")
    table.add_column("Updated / 更新时间")
    for address in addresses:
        table.add_row(
            address["email"],
            address["label"] or "",
            address["state"],
            _forwarding_label(address["is_active"]),
            address["source"],
            address["updated_at"],
        )
    Console().print(table)
    write_result_json(
        result_json,
        {"ok": True, "addresses": addresses, "error": None},
    )


def _icloud_timestamp(value) -> Optional[str]:
    """Converts iCloud's millisecond createTimestamp to an ISO string."""
    if not value:
        return None
    try:
        return datetime.datetime.fromtimestamp(
            value / 1000, tz=datetime.timezone.utc
        ).isoformat()
    except (TypeError, ValueError, OSError):
        return None


def _forwarding_label(is_active: Optional[bool]) -> str:
    if is_active is None:
        return "unknown / 未知"
    return "on / 开" if is_active else "off / 关"


@inboxgroup.command(name="mark")
@click.argument("email")
@click.argument("state", type=click.Choice(ADDRESS_STATES))
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_mark(email: str, state: str, db_file: str, result_json: Optional[str]):
    "Mark an address as unused, used, or trash / 标记地址状态"
    try:
        conn = connect_db(db_file)
        try:
            mark_address(conn, email, state)
        finally:
            conn.close()
    except Exception as e:
        write_result_json(
            result_json,
            {
                "ok": False,
                "email": email,
                "state": state,
                "error": bridge_error({"reason": str(e)}),
            },
        )
        raise click.ClickException(str(e)) from e
    Console().log(f'[bold green][OK][/] Marked "{email}" as {state} / 已标记地址状态')
    write_result_json(
        result_json,
        {"ok": True, "email": email, "state": state, "error": None},
    )


@inboxgroup.command(name="mark-read")
@click.argument("ids", nargs=-1, required=True, type=int)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_mark_read(ids: tuple, db_file: str, result_json: Optional[str]):
    "Mark inbox messages as read / 标记邮件为已读"
    try:
        conn = connect_db(db_file)
        try:
            updated = mark_messages_read(conn, ids)
            remaining = count_unread(conn)
        finally:
            conn.close()
    except Exception as e:
        write_result_json(
            result_json,
            {
                "ok": False,
                "count": 0,
                "unread": 0,
                "error": bridge_error({"reason": str(e)}),
            },
        )
        raise click.ClickException(str(e)) from e
    Console().log(
        f"[bold green][OK][/] Marked {updated} message(s) read / 已标记 {updated} 封邮件为已读"
    )
    write_result_json(
        result_json,
        {"ok": True, "count": updated, "unread": remaining, "error": None},
    )


@inboxgroup.command(name="export")
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option(
    "--export-dir",
    default="exports",
    show_default=True,
    type=click.Path(),
)
@click.option("--batch-id", help="Only export this batch / 仅导出此批次")
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_export(
    db_file: str, export_dir: str, batch_id: Optional[str], result_json: Optional[str]
):
    "Export local addresses and messages to CSV / 导出本地地址和邮件 CSV"
    try:
        outputs = export_csv_files(
            db_file=db_file, export_dir=export_dir, batch_id=batch_id
        )
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "outputs": {}, "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e
    console = Console()
    for name, path in outputs.items():
        console.log(f"[bold green][OK][/] Exported {name}: {path} / 已导出")
    write_result_json(
        result_json,
        {
            "ok": True,
            "outputs": {name: str(path) for name, path in outputs.items()},
            "error": None,
        },
    )


@inboxgroup.command(name="sync-hme")
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    show_default=True,
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use / iCloud 区域",
)
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def inbox_sync_hme(
    cookie_file: str, region: str, db_file: str, result_json: Optional[str]
):
    "Sync existing iCloud Hide My Email addresses into the local database / 同步已有 iCloud 隐藏邮箱到本地库"
    try:
        count = asyncio.run(_sync_hme_to_db(cookie_file, region, db_file))
    except KeyboardInterrupt:
        return
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "count": 0, "error": bridge_error({"reason": str(e)})},
        )
        raise
    Console().log(f"[bold green][OK][/] Synced {count} Hide My Email address(es) / 已同步 {count} 个隐藏邮箱")
    write_result_json(
        result_json,
        {"ok": True, "count": count, "error": None},
    )


async def _generate(
    label: str,
    count: int,
    cookie_file: str,
    output_file: str,
    no_output_file: bool = False,
    region: str = DEFAULT_REGION,
    db_file: str = DEFAULT_DB_FILE,
    no_db: bool = False,
    batch_id: Optional[str] = None,
) -> dict:
    async with RichHideMyEmail(
        cookie_file=cookie_file,
        output_file=output_file,
        no_output_file=no_output_file,
        region=region,
    ) as hme:
        emails = await hme.generate(label, count)

    if emails and not no_db:
        conn = connect_db(db_file)
        try:
            for email in emails:
                # No note: a canned one would overwrite whatever the user wrote.
                upsert_address(
                    conn,
                    email,
                    label=label,
                    state="unused",
                    source="generated",
                    batch_id=batch_id,
                )
        finally:
            conn.close()

    return {
        "ok": len(emails) == count,
        "emails": emails,
        "error": None
        if len(emails) == count
        else hme.last_error
        or {"code": None, "message": "Generation failed", "retry_after": None},
    }


async def _list(
    label_query: Optional[str],
    active: bool,
    cookie_file: str,
    region: str = DEFAULT_REGION,
) -> dict:
    async with RichHideMyEmail(cookie_file=cookie_file, region=region) as hme:
        return await hme.list(label_query, active)


def _run_address_command(
    coro, result_json: Optional[str], db_file: Optional[str] = None
) -> None:
    try:
        result = asyncio.run(coro)
    except KeyboardInterrupt:
        coro.close()
        return

    if result["ok"] and db_file:
        _write_through(db_file, result)
    write_result_json(result_json, result)
    if not result["ok"]:
        raise click.ClickException(result["error"]["message"])


def _write_through(db_file: str, result: dict) -> None:
    """Mirrors an accepted iCloud edit into the local database.

    Without this the address list keeps serving the pre-edit label, note, and
    forwarding state until the next full sync.
    """
    conn = connect_db(db_file)
    try:
        set_address_metadata(
            conn,
            result["email"],
            label=result.get("label"),
            note=result.get("note"),
            is_active=result.get("is_active"),
        )
    finally:
        conn.close()


async def _set_active(
    email: str, active: bool, cookie_file: str, region: str = DEFAULT_REGION
) -> dict:
    async with RichHideMyEmail(cookie_file=cookie_file, region=region) as hme:
        return await hme.set_active(email, active)


async def _update_metadata(
    email: str,
    label: Optional[str],
    note: Optional[str],
    cookie_file: str,
    region: str = DEFAULT_REGION,
) -> dict:
    async with RichHideMyEmail(cookie_file=cookie_file, region=region) as hme:
        return await hme.update_metadata(email, label, note)


async def _whoami(cookie_file: str, region: str = DEFAULT_REGION) -> dict:
    console = Console()
    if not os.path.exists(cookie_file):
        message = f'No "{cookie_file}" file found'
        console.log(f"[bold red][ERR][/] {message}")
        return {
            "ok": False,
            "account": None,
            "error": {"code": None, "message": message, "retry_after": None},
        }

    account = await fetch_account_info(cookie_file, region)
    if "error" in account:
        console.log(f"[bold red][ERR][/] {account['error']}")
        return {
            "ok": False,
            "account": None,
            "error": {
                "code": None,
                "message": account["error"],
                "retry_after": None,
            },
        }

    summary = account_summary(account)
    table = Table(title="Current iCloud Cookie / 当前 iCloud Cookie", show_header=False)
    table.add_column("Field / 字段")
    table.add_column("Value / 值")
    table.add_row("Apple ID", summary["apple_id"])
    table.add_row("Name / 名称", summary["name"])
    table.add_row("DSID", str(account.get("dsInfo", {}).get("dsid") or "Unknown"))
    table.add_row(
        "Hide My Email / 隐藏邮箱",
        "Available" if summary["hide_my_email_available"] else "Unavailable or unknown",
    )
    table.add_row(
        "User Partition / 用户分区", str(summary["user_partition"] or "Unknown")
    )
    table.add_row(
        "Maildomain",
        summary["maildomain_host"] or "Default",
    )
    console.print(table)
    return {"ok": True, "account": summary, "error": None}


def _field(row, name, default=None):
    """Reads a column from either a sqlite3.Row or a freshly built sync record."""
    if isinstance(row, dict):
        return row.get(name, default)
    return row[name] if name in row.keys() else default


def _message_payload(row) -> dict:
    return {
        "id": _field(row, "id"),
        "received_at": _field(row, "received_at"),
        "hme_address": _field(row, "hme_address"),
        "sender": _field(row, "sender"),
        "subject": _field(row, "subject"),
        "code": _field(row, "code"),
        "body_preview": _field(row, "body_preview"),
        # Records handed back straight after an IMAP sync are unread by definition.
        "is_read": bool(_field(row, "is_read", 0)),
    }


def _address_payload(row) -> dict:
    is_active = _field(row, "is_active")
    return {
        "email": _field(row, "email"),
        "label": _field(row, "label"),
        "state": _field(row, "state"),
        "source": _field(row, "source"),
        "note": _field(row, "note"),
        # NULL means the address has never been synced from iCloud.
        "is_active": None if is_active is None else bool(is_active),
        "batch_id": _field(row, "batch_id"),
        "created_at": _field(row, "created_at"),
        "updated_at": _field(row, "updated_at"),
    }


def _batch_payload(row) -> dict:
    return {
        "id": _field(row, "id"),
        "label": _field(row, "label"),
        "target": _field(row, "target"),
        "reserved": _field(row, "reserved", 0),
        "interval_seconds": _field(row, "interval_seconds"),
        "state": _field(row, "state"),
        "started_at": _field(row, "started_at"),
        "finished_at": _field(row, "finished_at"),
    }


def _print_messages(
    db_file: str, only_codes: bool, limit: int, only_unread: bool = False
) -> list[dict]:
    conn = connect_db(db_file)
    try:
        rows = list_messages(
            conn, only_codes=only_codes, limit=limit, only_unread=only_unread
        )
    finally:
        conn.close()

    table = Table(title="Verification Codes / 验证码" if only_codes else "Inbox Messages / 收件箱")
    table.add_column("Received / 收件时间")
    table.add_column("HME / 隐藏邮箱")
    table.add_column("Sender / 发件人")
    table.add_column("Subject / 标题")
    table.add_column("Code / 验证码")
    table.add_column("Read / 已读")
    for row in rows:
        table.add_row(
            row["received_at"] or "",
            row["hme_address"] or "",
            row["sender"] or "",
            row["subject"] or "",
            row["code"] or "",
            "" if row["is_read"] else "●",
        )
    Console().print(table)
    return [_message_payload(row) for row in rows]


async def _sync_hme_to_db(
    cookie_file: str, region: str = DEFAULT_REGION, db_file: str = DEFAULT_DB_FILE
) -> int:
    async with RichHideMyEmail(cookie_file=cookie_file, region=region) as hme:
        result = await hme.list_email()

    if not result or not result.get("success"):
        error = result.get("error", {}) if result else {}
        if isinstance(error, dict):
            reason = error.get("errorMessage") or str(error)
        else:
            reason = result.get("reason", "Unknown") if result else "Unknown"
        raise click.ClickException(f"Failed to sync Hide My Email addresses: {reason}")

    conn = connect_db(db_file)
    try:
        count = 0
        for row in result.get("result", {}).get("hmeEmails", []):
            email = row.get("hme")
            if not email:
                continue
            upsert_address(
                conn,
                email,
                label=row.get("label") or "",
                # Forwarding state is tracked on its own column now; collapsing it
                # into the local state would hide it behind the user's own filing.
                state="unused",
                source="icloud",
                note=row.get("note") or "",
                is_active=bool(row.get("isActive")),
                created_at=_icloud_timestamp(row.get("createTimestamp")),
            )
            count += 1
        return count
    finally:
        conn.close()


@click.group(name="batch")
def batchgroup():
    "Track long generation runs across restarts / 跟踪批量生成任务"
    pass


def _batch_db_option(f):
    return click.option(
        "--db-file",
        default=DEFAULT_DB_FILE,
        show_default=True,
        type=click.Path(),
    )(f)


def _print_batches(rows) -> list[dict]:
    batches = [_batch_payload(row) for row in rows]
    table = Table(title="Batches / 批次")
    table.add_column("ID")
    table.add_column("Label / 标签")
    table.add_column("Progress / 进度")
    table.add_column("State / 状态")
    table.add_column("Started / 开始时间")
    table.add_column("Finished / 结束时间")
    for batch in batches:
        table.add_row(
            batch["id"][:8],
            batch["label"],
            f"{batch['reserved']} / {batch['target']}",
            batch["state"],
            batch["started_at"],
            batch["finished_at"] or "",
        )
    Console().print(table)
    return batches


@batchgroup.command(name="start")
@click.option("--label", required=True, help="Label for every address / 地址标签")
@click.option("--target", required=True, type=int, help="How many to reserve / 目标数量")
@click.option(
    "--interval-minutes",
    type=int,
    help="Minutes to wait after Apple's rate limit / 触发限流后的等待分钟数",
)
@_batch_db_option
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_start(
    label: str,
    target: int,
    interval_minutes: Optional[int],
    db_file: str,
    result_json: Optional[str],
):
    "Create a batch and print its id / 创建批次"
    try:
        conn = connect_db(db_file)
        try:
            batch = create_batch(
                conn,
                label,
                target,
                interval_seconds=interval_minutes * 60 if interval_minutes else None,
            )
        finally:
            conn.close()
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "batch": None, "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e

    payload = _batch_payload(batch)
    Console().log(f"[bold green][OK][/] Created batch {payload['id']} / 已创建批次")
    write_result_json(result_json, {"ok": True, "batch": payload, "error": None})


@batchgroup.command(name="list")
@_batch_db_option
@click.option("--limit", default=50, show_default=True, type=int)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_list(db_file: str, limit: int, result_json: Optional[str]):
    "Show every batch / 查看所有批次"
    try:
        conn = connect_db(db_file)
        try:
            batches = _print_batches(list_batches(conn, limit=limit))
        finally:
            conn.close()
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "batches": [], "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e
    write_result_json(result_json, {"ok": True, "batches": batches, "error": None})


@batchgroup.command(name="status")
@click.argument("batch_id")
@_batch_db_option
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_status(batch_id: str, db_file: str, result_json: Optional[str]):
    "Show one batch and the addresses it reserved / 查看批次详情"
    conn = connect_db(db_file)
    try:
        batch = get_batch(conn, batch_id)
        if batch is None:
            message = f'No batch matching "{batch_id}" / 未找到批次'
            write_result_json(
                result_json,
                {
                    "ok": False,
                    "batch": None,
                    "addresses": [],
                    "error": bridge_error({"reason": message}),
                },
            )
            raise click.ClickException(message)
        payload = _batch_payload(batch)
        addresses = [
            _address_payload(row)
            for row in list_addresses(conn, batch_id=batch_id, limit=100_000)
        ]
    finally:
        conn.close()

    _print_batches([batch])
    write_result_json(
        result_json,
        {"ok": True, "batch": payload, "addresses": addresses, "error": None},
    )


def _transition(batch_id: str, db_file: str, state: str, result_json: Optional[str]):
    conn = connect_db(db_file)
    try:
        batch = set_batch_state(conn, batch_id, state)
    finally:
        conn.close()

    if batch is None:
        message = f'No batch matching "{batch_id}" / 未找到批次'
        write_result_json(
            result_json,
            {"ok": False, "batch": None, "error": bridge_error({"reason": message})},
        )
        raise click.ClickException(message)

    payload = _batch_payload(batch)
    Console().log(f"[bold green][OK][/] Batch is now {state} / 批次状态已更新")
    write_result_json(result_json, {"ok": True, "batch": payload, "error": None})


@batchgroup.command(name="pause")
@click.argument("batch_id")
@_batch_db_option
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_pause(batch_id: str, db_file: str, result_json: Optional[str]):
    "Pause a running batch / 暂停批次"
    _transition(batch_id, db_file, "paused", result_json)


@batchgroup.command(name="resume")
@click.argument("batch_id")
@_batch_db_option
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_resume(batch_id: str, db_file: str, result_json: Optional[str]):
    "Resume a paused batch / 恢复批次"
    _transition(batch_id, db_file, "running", result_json)


@batchgroup.command(name="stop")
@click.argument("batch_id")
@_batch_db_option
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_stop(batch_id: str, db_file: str, result_json: Optional[str]):
    "Stop a batch for good / 结束批次"
    _transition(batch_id, db_file, "stopped", result_json)


@batchgroup.command(name="export")
@click.argument("batch_id")
@_batch_db_option
@click.option(
    "--export-dir",
    default="exports",
    show_default=True,
    type=click.Path(),
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def batch_export(
    batch_id: str, db_file: str, export_dir: str, result_json: Optional[str]
):
    "Export one batch's addresses to CSV / 导出批次地址"
    try:
        outputs = export_csv_files(
            db_file=db_file, export_dir=export_dir, batch_id=batch_id
        )
    except Exception as e:
        write_result_json(
            result_json,
            {"ok": False, "outputs": {}, "error": bridge_error({"reason": str(e)})},
        )
        raise click.ClickException(str(e)) from e
    console = Console()
    for name, path in outputs.items():
        console.log(f"[bold green][OK][/] Exported {name}: {path} / 已导出")
    write_result_json(
        result_json,
        {
            "ok": True,
            "outputs": {name: str(path) for name, path in outputs.items()},
            "error": None,
        },
    )


@click.command()
@click.option(
    "--db-file",
    default=DEFAULT_DB_FILE,
    show_default=True,
    type=click.Path(),
)
@click.option("--result-json", type=click.Path(dir_okay=False), hidden=True)
def quotacommand(db_file: str, result_json: Optional[str]):
    "Estimate how many addresses Apple will still accept / 估算剩余可创建数量"
    window_start = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(
        seconds=RATE_LIMIT_WINDOW_SECONDS
    )
    conn = connect_db(db_file)
    try:
        used = count_addresses_since(conn, window_start.isoformat())
        oldest = conn.execute(
            "SELECT MIN(created_at) AS oldest FROM addresses WHERE created_at >= ?",
            (window_start.isoformat(),),
        ).fetchone()["oldest"]
    finally:
        conn.close()

    resets_at = None
    if oldest:
        try:
            resets_at = (
                datetime.datetime.fromisoformat(oldest)
                + datetime.timedelta(seconds=RATE_LIMIT_WINDOW_SECONDS)
            ).isoformat()
        except ValueError:
            resets_at = None

    remaining = max(0, RATE_LIMIT_PER_WINDOW - used)
    console = Console()
    console.log(
        f"[bold green][OK][/] About {remaining} of {RATE_LIMIT_PER_WINDOW} left this window "
        f"/ 本时段约剩 {remaining} 个"
    )
    console.log(
        "[dim]Estimated from addresses this database knows about; "
        "Apple does not publish the real quota. / 基于本地数据估算[/]"
    )
    write_result_json(
        result_json,
        {
            "ok": True,
            "used": used,
            "remaining": remaining,
            "limit": RATE_LIMIT_PER_WINDOW,
            "window_seconds": RATE_LIMIT_WINDOW_SECONDS,
            "resets_at": resets_at,
            "error": None,
        },
    )


async def _capture_cookie(cookie_file: str, region: str = DEFAULT_REGION) -> bool:
    console = Console()
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        if getattr(sys, "frozen", False):
            console.log(
                "[bold red][ERR][/] Auto capture is not available in the prebuilt binary. "
                "Run from source (uv sync --extra capture) or use manual cookie capture. / "
                "预构建二进制不支持自动获取，请使用源码运行或手动获取 Cookie。"
            )
        else:
            console.log(
                "[bold red][ERR][/] Playwright is not installed. Run: uv sync --extra capture"
            )
        return False

    profile_dir = Path(".cookie-browser-profile").resolve()
    profile_dir.mkdir(exist_ok=True)

    loop = asyncio.get_running_loop()
    captured = loop.create_future()

    async with async_playwright() as playwright:
        context = None
        last_error = None
        for channel in ["msedge", "chrome"]:
            try:
                context = await playwright.chromium.launch_persistent_context(
                    str(profile_dir),
                    channel=channel,
                    headless=False,
                    viewport={"width": 1280, "height": 900},
                )
                break
            except Exception as e:
                last_error = e

        if context is None:
            try:
                context = await playwright.chromium.launch_persistent_context(
                    str(profile_dir),
                    headless=False,
                    viewport={"width": 1280, "height": 900},
                )
            except Exception:
                console.log(
                    "[bold red][ERR][/] Could not start a browser. Install Microsoft Edge or run: uv run playwright install chromium"
                )
                if last_error:
                    console.log(f"[dim]{last_error}[/]")
                return False

        page = context.pages[0] if context.pages else await context.new_page()

        def on_request(request):
            if HIDEMYEMAIL_APP_PATH not in request.url:
                return
            if "rootDomain=www" not in request.url:
                return

            cookie = request.headers.get("cookie", "")
            if cookie and not captured.done():
                captured.set_result((request.url, cookie))

        context.on("request", on_request)

        console.print(
            "A browser window opened. Log in if needed; the tool will click Hide My Email and capture the request. / 已打开浏览器；如需登录请先登录，工具会点击隐藏邮件地址并捕获请求。"
        )
        await page.goto(COOKIE_CAPTURE_URLS[region], wait_until="domcontentloaded")

        clicked = False
        deadline = loop.time() + 300
        selectors = [
            'button[aria-label*="隐藏邮件地址"]',
            'button[aria-label*="Hide My Email"]',
            '[data-testid="hidemyemail-app-icon"]',
            "text=隐藏邮件地址",
            "text=Hide My Email",
        ]

        while not captured.done() and loop.time() < deadline:
            if not clicked:
                for selector in selectors:
                    locator = page.locator(selector).first
                    try:
                        if await locator.count():
                            await locator.click(timeout=2000)
                            clicked = True
                            break
                    except Exception:
                        continue
            await asyncio.sleep(1)

        if not captured.done():
            await context.close()
            console.log(
                "[bold red][ERR][/] Timed out waiting for the Hide My Email app request / 等待隐藏邮件地址应用请求超时"
            )
            return False

        request_url, cookie = captured.result()
        account = await fetch_account_info_from_cookie(cookie, region)
        if "error" in account:
            await context.close()
            console.log(f"[bold red][ERR][/] Captured cookie did not validate: {account['error']}")
            return False

        maildomain_host = account.get("detectedMaildomainHost") or ""
        write_captured_cookie(cookie_file, cookie, region, request_url, maildomain_host)
        await context.close()

    console.log(f'[bold green][OK][/] Captured and saved cookie to "{cookie_file}" / 已捕获并保存 Cookie')
    await _whoami(cookie_file, region)
    return True


cli.add_command(listcommand, name="list")
cli.add_command(generatecommand, name="generate")
cli.add_command(whoamicommand, name="whoami")
cli.add_command(capturecookiecommand, name="capture-cookie")
cli.add_command(deactivatecommand, name="deactivate")
cli.add_command(reactivatecommand, name="reactivate")
cli.add_command(updatemetadatacommand, name="update-metadata")
cli.add_command(quotacommand, name="quota")
cli.add_command(inboxgroup)
cli.add_command(batchgroup)

if __name__ == "__main__":
    cli()
