import asyncio
import base64
import datetime
import os
import shutil
from typing import Union, List, Optional
import re
import ssl
from pathlib import Path

import aiohttp
import certifi
import click
from rich.console import Console
from rich.table import Table

from hidemyemail_generator.hidemyemail import HideMyEmail


MAX_CONCURRENT_TASKS = 10
DEFAULT_COOKIE_FILENAME = "cookies.txt"
DEFAULT_EMAIL_FILENAME = "emails.txt"
DEFAULT_HME_NOTE = "Generated by rtuna's iCloud email generator"
DEFAULT_REGION = os.environ.get("HIDEMYEMAIL_REGION", "global").lower()
REGION_CHOICE = click.Choice(["global", "china"], case_sensitive=False)
SETUP_VALIDATE_URLS = {
    "global": "https://setup.icloud.com/setup/ws/1/validate",
    "china": "https://setup.icloud.com.cn/setup/ws/1/validate",
}
COOKIE_CAPTURE_URLS = {
    "global": "https://www.icloud.com/icloudplus/",
    "china": "https://www.icloud.com.cn/icloudplus/",
}
HIDEMYEMAIL_APP_PATH = "/applications/hidemyemail/current/"


def load_cookie_context(cookie_file: str, region: str) -> tuple[str, str]:
    with open(cookie_file, "r") as f:
        content = "\n".join(
            line.strip() for line in f if not line.lstrip().startswith("//")
        ).strip()
    normalized_content = (
        content.replace('^"', '"')
        .replace("^'", "'")
        .replace("^\n", "")
        .replace("^\r\n", "")
    )

    maildomain_host = ""
    explicit_maildomain_host = re.search(
        r"(?m)^HIDEMYEMAIL_MAILDOMAIN_HOST=([A-Za-z0-9.-]+)\s*$",
        normalized_content,
    )
    if explicit_maildomain_host:
        maildomain_host = explicit_maildomain_host.group(1).strip()

    encoded_cookie = re.search(
        r"(?m)^HIDEMYEMAIL_COOKIE_BASE64=([A-Za-z0-9+/=]+)\s*$",
        normalized_content,
    )
    if encoded_cookie:
        cookie = base64.b64decode(encoded_cookie.group(1)).decode("utf-8")
        return cookie.strip(), maildomain_host

    shard = re.search(
        r"https://(p\d+)-[^/\s'\"]+\.icloud\.com(?:\.cn)?", normalized_content
    )
    if shard:
        suffix = "com.cn" if region == "china" else "com"
        maildomain_host = f"{shard.group(1)}-maildomainws.icloud.{suffix}"

    cmd_cookie_arg = re.search(
        r"(?:^|\s)(?:-b|--cookie)\s+\^\"(.+?)\^\"\s+\^?\s*-[A-Za-z]",
        content,
        re.IGNORECASE | re.DOTALL,
    )
    if cmd_cookie_arg:
        cookie = (
            cmd_cookie_arg.group(1)
            .replace('^\\^"', '"')
            .replace('\\"', '"')
            .replace('^"', '"')
            .replace("\r", "")
            .replace("\n", "")
        )
        return cookie.strip(), maildomain_host

    cookie_arg = re.search(
        r"(?:^|\s)(?:-b|--cookie)\s+\"([^\"]+)\"",
        normalized_content,
        re.IGNORECASE,
    )
    if cookie_arg:
        return cookie_arg.group(1).strip(), maildomain_host

    cookie_header = re.search(
        r"cookie\s*:\s*([^'\"\r\n]+)", normalized_content, re.IGNORECASE
    )
    if cookie_header:
        return cookie_header.group(1).strip(), maildomain_host

    return normalized_content.splitlines()[0].strip(), maildomain_host


def load_cookie_string(cookie_file: str) -> str:
    return load_cookie_context(cookie_file, DEFAULT_REGION)[0]


async def fetch_account_info(cookie_file: str, region: str) -> dict:
    cookie, maildomain_host = load_cookie_context(cookie_file, region)
    if not cookie:
        return {"error": "Cookie file is empty"}

    return await fetch_account_info_from_cookie(cookie, region, maildomain_host)


async def fetch_account_info_from_cookie(
    cookie: str, region: str, maildomain_host: str = ""
) -> dict:
    headers = {
        "Cookie": cookie,
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36",
        "Origin": HideMyEmail.REGION_CONFIG[region]["web_origin"],
        "Referer": f"{HideMyEmail.REGION_CONFIG[region]['web_origin']}/",
        "Accept": "*/*",
    }
    connector = aiohttp.TCPConnector(
        ssl_context=ssl.create_default_context(cafile=certifi.where())
    )

    async with aiohttp.ClientSession(
        headers=headers,
        timeout=aiohttp.ClientTimeout(total=30),
        connector=connector,
    ) as session:
        async with session.get(SETUP_VALIDATE_URLS[region]) as response:
            try:
                data = await response.json(content_type=None)
            except Exception:
                return {"error": f"Unexpected response from iCloud ({response.status})"}

    if response.status != 200:
        reason = data.get("reason") or data.get("error") or response.status
        return {"error": f"Failed to validate cookie: {reason}"}

    user_partition = data.get("userPartition")
    if not maildomain_host and user_partition:
        suffix = "com.cn" if region == "china" else "com"
        maildomain_host = f"p{user_partition}-maildomainws.icloud.{suffix}"

    data["detectedMaildomainHost"] = maildomain_host
    return data


def write_captured_cookie(
    cookie_file: str, cookie: str, region: str, request_url: str, maildomain_host: str
) -> None:
    path = Path(cookie_file)
    if path.exists() and path.stat().st_size > 0:
        shutil.copy2(path, path.with_name(f"{path.name}.bak"))

    encoded_cookie = base64.b64encode(cookie.encode("utf-8")).decode("ascii")
    path.write_text(
        "\n".join(
            [
                "# Generated by hidemyemail capture-cookie.",
                f"HIDEMYEMAIL_REGION={region}",
                f"HIDEMYEMAIL_REQUEST_URL={request_url}",
                f"HIDEMYEMAIL_MAILDOMAIN_HOST={maildomain_host}",
                f"HIDEMYEMAIL_COOKIE_BASE64={encoded_cookie}",
                "",
            ]
        ),
        encoding="utf-8",
    )


class RichHideMyEmail(HideMyEmail):
    def __init__(
        self,
        cookie_file: str,
        output_file: str = "",
        no_output_file: bool = False,
        region: str = DEFAULT_REGION,
    ):
        cookies = ""
        maildomain_host = ""
        if os.path.exists(cookie_file):
            cookies, maildomain_host = load_cookie_context(cookie_file, region)

        super().__init__(cookies=cookies, region=region, maildomain_host=maildomain_host)
        self.console = Console()
        self.table = Table()
        self._output_file = output_file
        self._no_output_file = no_output_file

        if not os.path.exists(cookie_file):
            self.console.log(
                f'[bold yellow][WARN][/] No "{cookie_file}" file found! Generation might not work due to unauthorized access.'
            )
        elif "X-APPLE-WEBAUTH-USER" not in self.cookies:
            self.console.log(
                "[bold yellow][WARN][/] Cookie is missing X-APPLE-WEBAUTH-USER. Copy a logged-in iCloud settings request, preferably maildomainws or hme, not feedbackws/reportStats."
            )

    def _check_response(
        self, response: dict, action: str, email: Optional[str] = None
    ) -> bool:
        if not response:
            return False
        if "success" not in response or not response["success"]:
            error = response.get("error", {})
            err_msg = "Unknown"
            if isinstance(error, int) and "reason" in response:
                err_msg = response["reason"]
            elif isinstance(error, dict) and "errorMessage" in error:
                err_msg = error["errorMessage"]
            email_prefix = f' "{email}"' if email else ""
            self.console.log(
                f"[bold red][ERR][/]{email_prefix} - Failed to {action}. Reason: {err_msg}"
            )
            return False
        return True

    async def _generate_one(self, label: str) -> Union[str, None]:
        # First, generate an email
        gen_res = await self.generate_email()

        if not self._check_response(gen_res, "generate email"):
            return

        email = gen_res["result"]["hme"]
        self.console.log(f'[50%] "{email}" - Successfully generated')

        # Then, reserve it
        reserve_res = await self.reserve_email(email, label, DEFAULT_HME_NOTE)

        if not self._check_response(reserve_res, "reserve email", email):
            return

        self.console.log(f'[100%] "{email}" - Successfully reserved')
        return email

    async def _generate(self, label: str, num: int):
        tasks = []
        for _ in range(num):
            task = asyncio.ensure_future(self._generate_one(label))
            tasks.append(task)

        return filter(lambda e: e is not None, await asyncio.gather(*tasks))

    async def generate(self, label: str, count: int) -> List[str]:
        try:
            emails = []
            self.console.rule()
            if count < 1:
                self.console.log("Count should be >= 1")
                return emails
            self.console.log(f"Generating {count} email(s)...")
            self.console.rule()

            with self.console.status("[bold green]Generating iCloud email(s)..."):
                while count > 0:
                    batch = await self._generate(
                        label,
                        count if count < MAX_CONCURRENT_TASKS else MAX_CONCURRENT_TASKS,
                    )
                    count -= MAX_CONCURRENT_TASKS
                    emails += batch

            if len(emails) > 0:
                if not self._no_output_file:
                    with open(self._output_file, "a+") as f:
                        f.write(os.linesep.join(emails) + os.linesep)

                    self.console.rule()
                    self.console.log(
                        f':star: Emails have been saved into the "{self._output_file}" file'
                    )
                else:
                    self.console.rule()

                self.console.log(
                    f"[bold green]All done![/] Successfully generated [bold green]{len(emails)}[/] email(s)"
                )

            return emails
        except KeyboardInterrupt:
            return []

    async def list(self, label_query: Optional[str], active: bool) -> None:
        gen_res = await self.list_email()
        if not self._check_response(gen_res, "list emails"):
            return

        self.table.add_column("Label")
        self.table.add_column("Hide My Email")
        self.table.add_column("Created At")
        self.table.add_column("Is Active")

        for row in gen_res["result"]["hmeEmails"]:
            if row["isActive"] == active and (
                label_query is None or re.search(label_query, row["label"])
            ):
                self.table.add_row(
                    row["label"],
                    row["hme"],
                    str(datetime.datetime.fromtimestamp(row["createTimestamp"] / 1000)),
                    str(row["isActive"]),
                )

        self.console.print(self.table)


@click.group()
def cli():
    pass


@click.command()
@click.option("--count", default=1, help="How many emails to generate", type=int)
@click.option(
    "--label",
    required=True,
    help="Label to set for generated emails",
)
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file",
    type=click.Path(),
)
@click.option(
    "--output",
    default=DEFAULT_EMAIL_FILENAME,
    help="Path to output file for saving emails",
    type=click.Path(),
)
@click.option(
    "--no-output-file",
    is_flag=True,
    default=False,
    help="Do not save emails to an output file",
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use",
)
def generatecommand(
    count: int,
    label: str,
    cookie_file: str,
    output: str,
    no_output_file: bool,
    region: str,
):
    "Generate emails"
    try:
        asyncio.run(_generate(label, count, cookie_file, output, no_output_file, region))
    except KeyboardInterrupt:
        pass


@click.command()
@click.option(
    "--label-query",
    help='Query to search within the "Label" field',
)
@click.option(
    "--active/--inactive", default=True, help="Filter Active / Inactive emails"
)
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use",
)
def listcommand(label_query: Optional[str], active: bool, cookie_file: str, region: str):
    "List emails"
    try:
        asyncio.run(_list(label_query, active, cookie_file, region))
    except KeyboardInterrupt:
        pass


@click.command()
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use",
)
def whoamicommand(cookie_file: str, region: str):
    "Show the account represented by the saved cookie"
    try:
        ok = asyncio.run(_whoami(cookie_file, region))
    except KeyboardInterrupt:
        return

    if not ok:
        raise click.ClickException("Could not identify the saved iCloud cookie")


@click.command()
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file",
    type=click.Path(),
)
@click.option(
    "--region",
    default=DEFAULT_REGION,
    show_default=True,
    type=REGION_CHOICE,
    help="iCloud region to use",
)
def capturecookiecommand(cookie_file: str, region: str):
    "Open iCloud Plus and capture the Hide My Email request cookie"
    try:
        ok = asyncio.run(_capture_cookie(cookie_file, region))
    except KeyboardInterrupt:
        return

    if not ok:
        raise click.ClickException("Could not capture the iCloud cookie")


async def _generate(
    label: str,
    count: int,
    cookie_file: str,
    output_file: str,
    no_output_file: bool = False,
    region: str = DEFAULT_REGION,
) -> None:
    async with RichHideMyEmail(
        cookie_file=cookie_file,
        output_file=output_file,
        no_output_file=no_output_file,
        region=region,
    ) as hme:
        await hme.generate(label, count)


async def _list(
    label_query: Optional[str],
    active: bool,
    cookie_file: str,
    region: str = DEFAULT_REGION,
) -> None:
    async with RichHideMyEmail(cookie_file=cookie_file, region=region) as hme:
        await hme.list(label_query, active)


async def _whoami(cookie_file: str, region: str = DEFAULT_REGION) -> bool:
    console = Console()
    if not os.path.exists(cookie_file):
        console.log(f'[bold red][ERR][/] No "{cookie_file}" file found')
        return False

    account = await fetch_account_info(cookie_file, region)
    if "error" in account:
        console.log(f"[bold red][ERR][/] {account['error']}")
        return False

    ds_info = account.get("dsInfo", {})
    full_name = ds_info.get("fullName") or " ".join(
        part for part in [ds_info.get("firstName"), ds_info.get("lastName")] if part
    )
    webservices = account.get("webservices", {})
    maildomain = webservices.get("maildomainws", {})

    table = Table(title="Current iCloud Cookie", show_header=False)
    table.add_column("Field")
    table.add_column("Value")
    table.add_row("Apple ID", ds_info.get("appleId") or "Unknown")
    table.add_row("Name", full_name or "Unknown")
    table.add_row("DSID", str(ds_info.get("dsid") or "Unknown"))
    table.add_row(
        "Hide My Email",
        "Available"
        if ds_info.get("isHideMyEmailFeatureAvailable")
        else "Unavailable or unknown",
    )
    table.add_row("User Partition", str(account.get("userPartition") or "Unknown"))
    table.add_row(
        "Maildomain",
        account.get("detectedMaildomainHost")
        or maildomain.get("url")
        or "Default",
    )
    console.print(table)
    return True


async def _capture_cookie(cookie_file: str, region: str = DEFAULT_REGION) -> bool:
    console = Console()
    try:
        from playwright.async_api import async_playwright
    except ImportError:
        console.log("[bold red][ERR][/] Playwright is not installed. Run: uv sync")
        return False

    profile_dir = Path(".cookie-browser-profile").resolve()
    profile_dir.mkdir(exist_ok=True)

    loop = asyncio.get_running_loop()
    captured = loop.create_future()

    async with async_playwright() as playwright:
        context = None
        last_error = None
        for channel in ["msedge", "chrome"]:
            try:
                context = await playwright.chromium.launch_persistent_context(
                    str(profile_dir),
                    channel=channel,
                    headless=False,
                    viewport={"width": 1280, "height": 900},
                )
                break
            except Exception as e:
                last_error = e

        if context is None:
            try:
                context = await playwright.chromium.launch_persistent_context(
                    str(profile_dir),
                    headless=False,
                    viewport={"width": 1280, "height": 900},
                )
            except Exception:
                console.log(
                    "[bold red][ERR][/] Could not start a browser. Install Microsoft Edge or run: uv run playwright install chromium"
                )
                if last_error:
                    console.log(f"[dim]{last_error}[/]")
                return False

        page = context.pages[0] if context.pages else await context.new_page()

        def on_request(request):
            if HIDEMYEMAIL_APP_PATH not in request.url:
                return
            if "rootDomain=www" not in request.url:
                return

            cookie = request.headers.get("cookie", "")
            if cookie and not captured.done():
                captured.set_result((request.url, cookie))

        context.on("request", on_request)

        console.print(
            "A browser window opened. Log in if needed; the tool will click Hide My Email and capture the request."
        )
        await page.goto(COOKIE_CAPTURE_URLS[region], wait_until="domcontentloaded")

        clicked = False
        deadline = loop.time() + 300
        selectors = [
            'button[aria-label*="隐藏邮件地址"]',
            'button[aria-label*="Hide My Email"]',
            '[data-testid="hidemyemail-app-icon"]',
            "text=隐藏邮件地址",
            "text=Hide My Email",
        ]

        while not captured.done() and loop.time() < deadline:
            if not clicked:
                for selector in selectors:
                    locator = page.locator(selector).first
                    try:
                        if await locator.count():
                            await locator.click(timeout=2000)
                            clicked = True
                            break
                    except Exception:
                        continue
            await asyncio.sleep(1)

        if not captured.done():
            await context.close()
            console.log(
                "[bold red][ERR][/] Timed out waiting for the Hide My Email app request"
            )
            return False

        request_url, cookie = captured.result()
        account = await fetch_account_info_from_cookie(cookie, region)
        if "error" in account:
            await context.close()
            console.log(f"[bold red][ERR][/] Captured cookie did not validate: {account['error']}")
            return False

        maildomain_host = account.get("detectedMaildomainHost") or ""
        write_captured_cookie(cookie_file, cookie, region, request_url, maildomain_host)
        await context.close()

    console.log(f'[bold green][OK][/] Captured and saved cookie to "{cookie_file}"')
    await _whoami(cookie_file, region)
    return True


cli.add_command(listcommand, name="list")
cli.add_command(generatecommand, name="generate")
cli.add_command(whoamicommand, name="whoami")
cli.add_command(capturecookiecommand, name="capture-cookie")

if __name__ == "__main__":
    cli()
