import asyncio
import datetime
import os
from typing import Union, List, Optional
import re

import click
from rich.console import Console
from rich.table import Table

from hidemyemail_generator.hidemyemail import HideMyEmail


MAX_CONCURRENT_TASKS = 10
DEFAULT_COOKIE_FILENAME = "cookies.txt"
DEFAULT_EMAIL_FILENAME = "emails.txt"
DEFAULT_HME_NOTE = "Generated by rtuna's iCloud email generator"


class RichHideMyEmail(HideMyEmail):
    def __init__(
        self, cookie_file: str, output_file: str = "", no_output_file: bool = False
    ):
        super().__init__()
        self.console = Console()
        self.table = Table()
        self._output_file = output_file
        self._no_output_file = no_output_file

        if os.path.exists(cookie_file):
            with open(cookie_file, "r") as f:
                self.cookies = [line for line in f if not line.startswith("//")][0]
        else:
            self.console.log(
                f'[bold yellow][WARN][/] No "{cookie_file}" file found! Generation might not work due to unauthorized access.'
            )

    def _check_response(
        self, response: dict, action: str, email: Optional[str] = None
    ) -> bool:
        if not response:
            return False
        if "success" not in response or not response["success"]:
            error = response.get("error", {})
            err_msg = "Unknown"
            if isinstance(error, int) and "reason" in response:
                err_msg = response["reason"]
            elif isinstance(error, dict) and "errorMessage" in error:
                err_msg = error["errorMessage"]
            email_prefix = f' "{email}"' if email else ""
            self.console.log(
                f"[bold red][ERR][/]{email_prefix} - Failed to {action}. Reason: {err_msg}"
            )
            return False
        return True

    async def _generate_one(self, label: str) -> Union[str, None]:
        # First, generate an email
        gen_res = await self.generate_email()

        if not self._check_response(gen_res, "generate email"):
            return

        email = gen_res["result"]["hme"]
        self.console.log(f'[50%] "{email}" - Successfully generated')

        # Then, reserve it
        reserve_res = await self.reserve_email(email, label, DEFAULT_HME_NOTE)

        if not self._check_response(reserve_res, "reserve email", email):
            return

        self.console.log(f'[100%] "{email}" - Successfully reserved')
        return email

    async def _generate(self, label: str, num: int):
        tasks = []
        for _ in range(num):
            task = asyncio.ensure_future(self._generate_one(label))
            tasks.append(task)

        return filter(lambda e: e is not None, await asyncio.gather(*tasks))

    async def generate(self, label: str, count: int) -> List[str]:
        try:
            emails = []
            self.console.rule()
            if count < 1:
                self.console.log("Count should be >= 1")
                return emails
            self.console.log(f"Generating {count} email(s)...")
            self.console.rule()

            with self.console.status("[bold green]Generating iCloud email(s)..."):
                while count > 0:
                    batch = await self._generate(
                        label,
                        count if count < MAX_CONCURRENT_TASKS else MAX_CONCURRENT_TASKS,
                    )
                    count -= MAX_CONCURRENT_TASKS
                    emails += batch

            if len(emails) > 0:
                if not self._no_output_file:
                    with open(self._output_file, "a+") as f:
                        f.write(os.linesep.join(emails) + os.linesep)

                    self.console.rule()
                    self.console.log(
                        f':star: Emails have been saved into the "{self._output_file}" file'
                    )
                else:
                    self.console.rule()

                self.console.log(
                    f"[bold green]All done![/] Successfully generated [bold green]{len(emails)}[/] email(s)"
                )

            return emails
        except KeyboardInterrupt:
            return []

    async def list(self, label_query: Optional[str], active: bool) -> None:
        gen_res = await self.list_email()
        if not self._check_response(gen_res, "list emails"):
            return

        self.table.add_column("Label")
        self.table.add_column("Hide My Email")
        self.table.add_column("Created At")
        self.table.add_column("Is Active")

        for row in gen_res["result"]["hmeEmails"]:
            if row["isActive"] == active and (
                label_query is None or re.search(label_query, row["label"])
            ):
                self.table.add_row(
                    row["label"],
                    row["hme"],
                    str(datetime.datetime.fromtimestamp(row["createTimestamp"] / 1000)),
                    str(row["isActive"]),
                )

        self.console.print(self.table)


@click.group()
def cli():
    pass


@click.command()
@click.option("--count", default=1, help="How many emails to generate", type=int)
@click.option(
    "--label",
    required=True,
    help="Label to set for generated emails",
)
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file",
    type=click.Path(),
)
@click.option(
    "--output",
    default=DEFAULT_EMAIL_FILENAME,
    help="Path to output file for saving emails",
    type=click.Path(),
)
@click.option(
    "--no-output-file",
    is_flag=True,
    default=False,
    help="Do not save emails to an output file",
)
def generatecommand(
    count: int, label: str, cookie_file: str, output: str, no_output_file: bool
):
    "Generate emails"
    try:
        asyncio.run(_generate(label, count, cookie_file, output, no_output_file))
    except KeyboardInterrupt:
        pass


@click.command()
@click.option(
    "--label-query",
    help='Query to search within the "Label" field',
)
@click.option(
    "--active/--inactive", default=True, help="Filter Active / Inactive emails"
)
@click.option(
    "--cookie-file",
    default=DEFAULT_COOKIE_FILENAME,
    help="Path to cookie file",
    type=click.Path(),
)
def listcommand(label_query: Optional[str], active: bool, cookie_file: str):
    "List emails"
    try:
        asyncio.run(_list(label_query, active, cookie_file))
    except KeyboardInterrupt:
        pass


async def _generate(
    label: str,
    count: int,
    cookie_file: str,
    output_file: str,
    no_output_file: bool = False,
) -> None:
    async with RichHideMyEmail(
        cookie_file=cookie_file, output_file=output_file, no_output_file=no_output_file
    ) as hme:
        await hme.generate(label, count)


async def _list(
    label_query: Optional[str],
    active: bool,
    cookie_file: str,
) -> None:
    async with RichHideMyEmail(cookie_file=cookie_file) as hme:
        await hme.list(label_query, active)


cli.add_command(listcommand, name="list")
cli.add_command(generatecommand, name="generate")

if __name__ == "__main__":
    cli()
