package com.hidemyemail.generator

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.util.Base64
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountCircle
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Email
import androidx.compose.material.icons.filled.Inbox
import androidx.compose.material.icons.filled.Language
import androidx.compose.material.icons.filled.OpenInBrowser
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Save
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Verified
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Divider
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.concurrent.TimeUnit

private const val DefaultNote = "Generated by HideMyEmail Android"

enum class ICloudRegion(val id: String, val title: String, val origin: String, val defaultMaildomain: String) {
    Global("global", "Global", "https://www.icloud.com", "p68-maildomainws.icloud.com"),
    China("china", "中国区", "https://www.icloud.com.cn", "p217-maildomainws.icloud.com.cn");

    companion object {
        fun from(value: String): ICloudRegion = values().firstOrNull { it.id == value } ?: Global
    }
}

data class CookieContext(
    val cookie: String,
    val maildomainHost: String = "",
)

data class AccountInfo(
    val appleId: String,
    val fullName: String,
    val dsid: String,
    val userPartition: String,
    val maildomainHost: String,
    val hideMyEmailAvailable: Boolean,
) {
    fun summary(): String {
        val name = fullName.ifBlank { "Unknown" }
        val hme = if (hideMyEmailAvailable) "Available" else "Unknown"
        return "Apple ID: $appleId\nName: $name\nDSID: $dsid\nPartition: $userPartition\nMaildomain: $maildomainHost\nHide My Email: $hme"
    }
}

data class HmeAddress(
    val email: String,
    val label: String,
    val active: Boolean,
    val createdAt: Long,
) {
    fun createdAtText(): String {
        if (createdAt <= 0) return ""
        return SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date(createdAt))
    }
}

data class LocalAddress(
    val email: String,
    val label: String,
    val state: String,
    val updatedAt: Long,
)

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HideMyEmailTheme {
                HideMyEmailApp()
            }
        }
    }
}

@Composable
private fun HideMyEmailTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = lightColorScheme(
            primary = Color(0xFF116A7B),
            secondary = Color(0xFF8A5A12),
            tertiary = Color(0xFF6750A4),
            background = Color(0xFFF8FAFC),
            surface = Color.White,
            surfaceVariant = Color(0xFFE7EEF2),
            onPrimary = Color.White,
        ),
        content = content,
    )
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun HideMyEmailApp() {
    val context = LocalContext.current
    val store = remember { HmeStore(context) }
    val repository = remember { HmeRepository() }
    val scope = rememberCoroutineScope()
    val localAddresses = remember { mutableStateListOf<LocalAddress>() }
    val remoteAddresses = remember { mutableStateListOf<HmeAddress>() }
    val generatedAddresses = remember { mutableStateListOf<HmeAddress>() }

    var selectedTab by remember { mutableStateOf(0) }
    var region by remember { mutableStateOf(store.loadRegion()) }
    var cookieInput by remember { mutableStateOf(store.loadCookie()) }
    var maildomainHost by remember { mutableStateOf(store.loadMaildomainHost()) }
    var accountSummary by remember { mutableStateOf("") }
    var label by remember { mutableStateOf("generated") }
    var countText by remember { mutableStateOf("1") }
    var showActive by remember { mutableStateOf(true) }
    var busy by remember { mutableStateOf(false) }
    var message by remember { mutableStateOf("准备就绪") }

    fun refreshLocal() {
        localAddresses.clear()
        localAddresses.addAll(store.loadLocalAddresses())
    }

    fun currentCookieContext(): CookieContext {
        val parsed = HmeRepository.parseCookieContext(cookieInput, region)
        return if (maildomainHost.isNotBlank()) {
            parsed.copy(maildomainHost = maildomainHost.trim())
        } else {
            parsed
        }
    }

    fun saveSettings() {
        val detectedRegion = HmeRepository.detectRegion(cookieInput) ?: region
        region = detectedRegion
        store.saveSettings(detectedRegion, cookieInput, maildomainHost)
        message = "已保存本地配置"
    }

    LaunchedEffect(Unit) {
        refreshLocal()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("HideMyEmail", fontWeight = FontWeight.SemiBold)
                        Text(
                            "iCloud 隐藏邮箱本地客户端",
                            style = MaterialTheme.typography.labelMedium,
                            color = MaterialTheme.colorScheme.secondary,
                        )
                    }
                },
            )
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background)
                .padding(padding),
        ) {
            TabRow(selectedTabIndex = selectedTab) {
                listOf("配置", "生成", "地址", "本地").forEachIndexed { index, title ->
                    Tab(selected = selectedTab == index, onClick = { selectedTab = index }, text = { Text(title) })
                }
            }

            StatusBar(message = message, busy = busy)

            when (selectedTab) {
                0 -> SettingsScreen(
                    region = region,
                    onRegionChange = {
                        region = it
                        if (maildomainHost == ICloudRegion.Global.defaultMaildomain ||
                            maildomainHost == ICloudRegion.China.defaultMaildomain
                        ) {
                            maildomainHost = ""
                        }
                    },
                    cookieInput = cookieInput,
                    onCookieChange = { cookieInput = it },
                    maildomainHost = maildomainHost,
                    onMaildomainChange = { maildomainHost = it },
                    accountSummary = accountSummary,
                    onSave = ::saveSettings,
                    onOpenICloud = {
                        context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("${region.origin}/icloudplus/")))
                    },
                    onValidate = {
                        saveSettings()
                        val requestRegion = HmeRepository.detectRegion(cookieInput) ?: region
                        region = requestRegion
                        scope.launch {
                            busy = true
                            message = "正在校验 Cookie..."
                            val result = runCatching {
                                withContext(Dispatchers.IO) {
                                    repository.fetchAccountInfo(currentCookieContext(), requestRegion)
                                }
                            }
                            result.onSuccess { account ->
                                accountSummary = account.summary()
                                maildomainHost = account.maildomainHost
                                store.saveSettings(requestRegion, cookieInput, maildomainHost)
                                message = "Cookie 可用：${account.appleId}"
                            }.onFailure {
                                message = it.cleanMessage()
                            }
                            busy = false
                        }
                    },
                )

                1 -> GenerateScreen(
                    label = label,
                    onLabelChange = { label = it },
                    countText = countText,
                    onCountChange = { countText = it.filter(Char::isDigit).take(2) },
                    generatedAddresses = generatedAddresses,
                    onGenerate = {
                        saveSettings()
                        val requestRegion = HmeRepository.detectRegion(cookieInput) ?: region
                        region = requestRegion
                        val count = countText.toIntOrNull()?.coerceIn(1, 20) ?: 1
                        scope.launch {
                            busy = true
                            generatedAddresses.clear()
                            message = "正在生成 $count 个隐藏邮箱..."
                            val result = runCatching {
                                withContext(Dispatchers.IO) {
                                    repository.generate(currentCookieContext(), requestRegion, label.ifBlank { "generated" }, count)
                                }
                            }
                            result.onSuccess { addresses ->
                                generatedAddresses.addAll(addresses)
                                store.upsertLocalAddresses(addresses.map {
                                    LocalAddress(it.email, it.label, "unused", System.currentTimeMillis())
                                })
                                refreshLocal()
                                message = "已生成 ${addresses.size} 个地址"
                            }.onFailure {
                                message = it.cleanMessage()
                            }
                            busy = false
                        }
                    },
                )

                2 -> RemoteListScreen(
                    showActive = showActive,
                    onModeChange = { showActive = it },
                    addresses = remoteAddresses.filter { it.active == showActive },
                    onRefresh = {
                        saveSettings()
                        val requestRegion = HmeRepository.detectRegion(cookieInput) ?: region
                        region = requestRegion
                        scope.launch {
                            busy = true
                            message = "正在读取 iCloud 地址..."
                            val result = runCatching {
                                withContext(Dispatchers.IO) {
                                    repository.listAddresses(currentCookieContext(), requestRegion)
                                }
                            }
                            result.onSuccess { addresses ->
                                remoteAddresses.clear()
                                remoteAddresses.addAll(addresses)
                                store.upsertLocalAddresses(addresses.map {
                                    LocalAddress(
                                        email = it.email,
                                        label = it.label,
                                        state = if (it.active) "unused" else "trash",
                                        updatedAt = System.currentTimeMillis(),
                                    )
                                })
                                refreshLocal()
                                message = "已读取 ${addresses.size} 个 iCloud 地址"
                            }.onFailure {
                                message = it.cleanMessage()
                            }
                            busy = false
                        }
                    },
                )

                3 -> LocalScreen(
                    addresses = localAddresses,
                    onMark = { email, state ->
                        store.markAddress(email, state)
                        refreshLocal()
                        message = "已标记 $email 为 $state"
                    },
                    onClear = {
                        store.clearLocalAddresses()
                        refreshLocal()
                        message = "已清空本地地址记录"
                    },
                )
            }
        }
    }
}

@Composable
private fun StatusBar(message: String, busy: Boolean) {
    Surface(
        tonalElevation = 1.dp,
        color = MaterialTheme.colorScheme.surface,
        modifier = Modifier.fillMaxWidth(),
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 10.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            if (busy) {
                CircularProgressIndicator(modifier = Modifier.width(18.dp).height(18.dp), strokeWidth = 2.dp)
            } else {
                Icon(Icons.Default.Verified, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
            }
            Text(message, style = MaterialTheme.typography.bodyMedium, maxLines = 2, overflow = TextOverflow.Ellipsis)
        }
    }
}

@Composable
private fun SettingsScreen(
    region: ICloudRegion,
    onRegionChange: (ICloudRegion) -> Unit,
    cookieInput: String,
    onCookieChange: (String) -> Unit,
    maildomainHost: String,
    onMaildomainChange: (String) -> Unit,
    accountSummary: String,
    onSave: () -> Unit,
    onOpenICloud: () -> Unit,
    onValidate: () -> Unit,
) {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp),
    ) {
        SectionCard(title = "区域", icon = Icons.Default.Language) {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                ICloudRegion.values().forEach { item ->
                    RegionButton(item, selected = region == item, onClick = { onRegionChange(item) })
                }
            }
        }

        SectionCard(title = "Cookie", icon = Icons.Default.Settings) {
            OutlinedTextField(
                value = cookieInput,
                onValueChange = onCookieChange,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(190.dp),
                minLines = 5,
                label = { Text("Cookie Header 或 Copy as cURL") },
            )
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(
                value = maildomainHost,
                onValueChange = onMaildomainChange,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                label = { Text("Maildomain host，可留空自动检测") },
                placeholder = { Text(region.defaultMaildomain) },
            )
            Spacer(Modifier.height(12.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                IconButtonText("保存", Icons.Default.Save, onSave)
                IconButtonText("校验账号", Icons.Default.AccountCircle, onValidate)
                OutlinedIconButtonText("打开 iCloud", Icons.Default.OpenInBrowser, onOpenICloud)
            }
        }

        if (accountSummary.isNotBlank()) {
            SectionCard(title = "当前账号", icon = Icons.Default.AccountCircle) {
                Text(accountSummary, style = MaterialTheme.typography.bodyMedium)
            }
        }
    }
}

@Composable
private fun GenerateScreen(
    label: String,
    onLabelChange: (String) -> Unit,
    countText: String,
    onCountChange: (String) -> Unit,
    generatedAddresses: List<HmeAddress>,
    onGenerate: () -> Unit,
) {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp),
    ) {
        SectionCard(title = "生成隐藏邮箱", icon = Icons.Default.Add) {
            OutlinedTextField(
                value = label,
                onValueChange = onLabelChange,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                label = { Text("Label") },
            )
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(
                value = countText,
                onValueChange = onCountChange,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                label = { Text("数量，1-20") },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            )
            Spacer(Modifier.height(12.dp))
            IconButtonText("生成", Icons.Default.Add, onGenerate)
        }

        if (generatedAddresses.isNotEmpty()) {
            SectionCard(title = "本次生成", icon = Icons.Default.Email) {
                generatedAddresses.forEach { AddressRow(it.email, it.label, it.createdAtText(), it.active) }
            }
        }
    }
}

@Composable
private fun RemoteListScreen(
    showActive: Boolean,
    onModeChange: (Boolean) -> Unit,
    addresses: List<HmeAddress>,
    onRefresh: () -> Unit,
) {
    Column(modifier = Modifier.fillMaxSize()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            SectionCard(title = "iCloud 地址", icon = Icons.Default.Inbox) {
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    RegionButton("使用中", selected = showActive, onClick = { onModeChange(true) })
                    RegionButton("已停用", selected = !showActive, onClick = { onModeChange(false) })
                }
                Spacer(Modifier.height(12.dp))
                IconButtonText("刷新", Icons.Default.Refresh, onRefresh)
            }
        }

        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            items(addresses, key = { it.email }) { item ->
                AddressCard(item)
            }
        }
    }
}

@Composable
private fun LocalScreen(
    addresses: List<LocalAddress>,
    onMark: (String, String) -> Unit,
    onClear: () -> Unit,
) {
    Column(modifier = Modifier.fillMaxSize()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            SectionCard(title = "本地状态", icon = Icons.Default.Inbox) {
                Text("未使用 ${addresses.count { it.state == "unused" }}  已使用 ${addresses.count { it.state == "used" }}  垃圾箱 ${addresses.count { it.state == "trash" }}")
                Spacer(Modifier.height(10.dp))
                OutlinedIconButtonText("清空本地记录", Icons.Default.Refresh, onClear)
            }
        }

        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            items(addresses, key = { it.email }) { item ->
                LocalAddressCard(item, onMark)
            }
        }
    }
}

@Composable
private fun SectionCard(
    title: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    content: @Composable () -> Unit,
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Icon(icon, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
                Text(title, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
            }
            Spacer(Modifier.height(12.dp))
            content()
        }
    }
}

@Composable
private fun RegionButton(region: ICloudRegion, selected: Boolean, onClick: () -> Unit) {
    RegionButton(region.title, selected, onClick)
}

@Composable
private fun RegionButton(text: String, selected: Boolean, onClick: () -> Unit) {
    val colors = if (selected) {
        ButtonDefaults.buttonColors()
    } else {
        ButtonDefaults.outlinedButtonColors()
    }
    if (selected) {
        Button(onClick = onClick, colors = colors, shape = RoundedCornerShape(8.dp)) { Text(text) }
    } else {
        OutlinedButton(onClick = onClick, colors = colors, shape = RoundedCornerShape(8.dp)) { Text(text) }
    }
}

@Composable
private fun IconButtonText(text: String, icon: androidx.compose.ui.graphics.vector.ImageVector, onClick: () -> Unit) {
    Button(onClick = onClick, shape = RoundedCornerShape(8.dp)) {
        Icon(icon, contentDescription = null)
        Spacer(Modifier.width(8.dp))
        Text(text)
    }
}

@Composable
private fun OutlinedIconButtonText(text: String, icon: androidx.compose.ui.graphics.vector.ImageVector, onClick: () -> Unit) {
    OutlinedButton(onClick = onClick, shape = RoundedCornerShape(8.dp)) {
        Icon(icon, contentDescription = null)
        Spacer(Modifier.width(8.dp))
        Text(text)
    }
}

@Composable
private fun AddressCard(address: HmeAddress) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
    ) {
        AddressRow(address.email, address.label, address.createdAtText(), address.active)
    }
}

@Composable
private fun AddressRow(email: String, label: String, meta: String, active: Boolean) {
    val context = LocalContext.current
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(14.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(email, fontWeight = FontWeight.SemiBold, maxLines = 1, overflow = TextOverflow.Ellipsis)
            Text(
                listOf(label, meta, if (active) "active" else "inactive").filter { it.isNotBlank() }.joinToString(" · "),
                style = MaterialTheme.typography.bodySmall,
                color = Color(0xFF64748B),
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
            )
        }
        OutlinedButton(
            onClick = { context.copyToClipboard(email) },
            contentPadding = PaddingValues(horizontal = 12.dp, vertical = 8.dp),
            shape = RoundedCornerShape(8.dp),
        ) {
            Icon(Icons.Default.ContentCopy, contentDescription = null)
        }
    }
}

@Composable
private fun LocalAddressCard(address: LocalAddress, onMark: (String, String) -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
    ) {
        Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            AddressRow(address.email, address.label, address.state, address.state != "trash")
            Divider()
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedButton(onClick = { onMark(address.email, "unused") }, shape = RoundedCornerShape(8.dp)) { Text("未使用") }
                OutlinedButton(onClick = { onMark(address.email, "used") }, shape = RoundedCornerShape(8.dp)) { Text("已使用") }
                OutlinedButton(onClick = { onMark(address.email, "trash") }, shape = RoundedCornerShape(8.dp)) { Text("垃圾箱") }
            }
        }
    }
}

class HmeStore(context: Context) {
    private val prefs = context.getSharedPreferences("hme-store", Context.MODE_PRIVATE)

    fun loadRegion(): ICloudRegion = ICloudRegion.from(prefs.getString("region", ICloudRegion.Global.id).orEmpty())

    fun loadCookie(): String = prefs.getString("cookie", "").orEmpty()

    fun loadMaildomainHost(): String = prefs.getString("maildomainHost", "").orEmpty()

    fun saveSettings(region: ICloudRegion, cookie: String, maildomainHost: String) {
        prefs.edit()
            .putString("region", region.id)
            .putString("cookie", cookie)
            .putString("maildomainHost", maildomainHost.trim())
            .apply()
    }

    fun loadLocalAddresses(): List<LocalAddress> {
        val raw = prefs.getString("localAddresses", "[]").orEmpty()
        val array = runCatching { JSONArray(raw) }.getOrElse { JSONArray() }
        return buildList {
            for (index in 0 until array.length()) {
                val item = array.optJSONObject(index) ?: continue
                add(
                    LocalAddress(
                        email = item.optString("email"),
                        label = item.optString("label"),
                        state = item.optString("state", "unused"),
                        updatedAt = item.optLong("updatedAt"),
                    )
                )
            }
        }.filter { it.email.isNotBlank() }.sortedByDescending { it.updatedAt }
    }

    fun upsertLocalAddresses(addresses: List<LocalAddress>) {
        val current = loadLocalAddresses().associateBy { it.email }.toMutableMap()
        addresses.forEach { address ->
            val existing = current[address.email]
            current[address.email] = address.copy(
                label = address.label.ifBlank { existing?.label.orEmpty() },
                state = if (existing?.state == "used") existing.state else address.state,
                updatedAt = System.currentTimeMillis(),
            )
        }
        saveLocalAddresses(current.values.sortedByDescending { it.updatedAt })
    }

    fun markAddress(email: String, state: String) {
        val current = loadLocalAddresses().map {
            if (it.email == email) it.copy(state = state, updatedAt = System.currentTimeMillis()) else it
        }
        saveLocalAddresses(current)
    }

    fun clearLocalAddresses() {
        prefs.edit().putString("localAddresses", "[]").apply()
    }

    private fun saveLocalAddresses(addresses: Collection<LocalAddress>) {
        val array = JSONArray()
        addresses.forEach { address ->
            array.put(
                JSONObject()
                    .put("email", address.email)
                    .put("label", address.label)
                    .put("state", address.state)
                    .put("updatedAt", address.updatedAt)
            )
        }
        prefs.edit().putString("localAddresses", array.toString()).apply()
    }
}

class HmeRepository {
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    fun fetchAccountInfo(context: CookieContext, region: ICloudRegion): AccountInfo {
        require(context.cookie.isNotBlank()) { "Cookie 为空" }
        val url = when (region) {
            ICloudRegion.Global -> "https://setup.icloud.com/setup/ws/1/validate"
            ICloudRegion.China -> "https://setup.icloud.com.cn/setup/ws/1/validate"
        }
        val response = client.newCall(baseRequest(url, context.cookie, region).get().build()).execute()
        val body = response.body?.string().orEmpty()
        if (!response.isSuccessful) error("iCloud 校验失败：${response.code}")
        val data = JSONObject(body)
        val dsInfo = data.optJSONObject("dsInfo") ?: JSONObject()
        val webservices = data.optJSONObject("webservices") ?: JSONObject()
        val maildomain = webservices.optJSONObject("maildomainws")
        val partition = data.optString("userPartition")
        val detectedHost = context.maildomainHost.ifBlank {
            when {
                maildomain?.optString("url").orEmpty().isNotBlank() -> Uri.parse(maildomain?.optString("url")).host.orEmpty()
                partition.isNotBlank() -> "p$partition-maildomainws.icloud.${if (region == ICloudRegion.China) "com.cn" else "com"}"
                else -> region.defaultMaildomain
            }
        }
        val name = listOf(dsInfo.optString("firstName"), dsInfo.optString("lastName"))
            .filter { it.isNotBlank() }
            .joinToString(" ")
            .ifBlank { dsInfo.optString("fullName") }

        return AccountInfo(
            appleId = dsInfo.optString("appleId", "Unknown"),
            fullName = name,
            dsid = dsInfo.optString("dsid", "Unknown"),
            userPartition = partition.ifBlank { "Unknown" },
            maildomainHost = detectedHost.ifBlank { region.defaultMaildomain },
            hideMyEmailAvailable = dsInfo.optBoolean("isHideMyEmailFeatureAvailable"),
        )
    }

    fun generate(context: CookieContext, region: ICloudRegion, label: String, count: Int): List<HmeAddress> {
        require(context.cookie.isNotBlank()) { "Cookie 为空" }
        val host = resolveMaildomainHost(context, region)
        val out = mutableListOf<HmeAddress>()
        repeat(count) {
            val generated = requestJson(
                method = "POST",
                url = "https://$host/v1/hme/generate",
                region = region,
                cookie = context.cookie,
                payload = JSONObject().put("langCode", "en-us"),
            )
            ensureSuccess(generated, "generate email")
            val email = generated.getJSONObject("result").getString("hme")
            val reserved = requestJson(
                method = "POST",
                url = "https://$host/v1/hme/reserve",
                region = region,
                cookie = context.cookie,
                payload = JSONObject()
                    .put("hme", email)
                    .put("label", label)
                    .put("note", DefaultNote),
            )
            ensureSuccess(reserved, "reserve email")
            out.add(HmeAddress(email = email, label = label, active = true, createdAt = System.currentTimeMillis()))
        }
        return out
    }

    fun listAddresses(context: CookieContext, region: ICloudRegion): List<HmeAddress> {
        require(context.cookie.isNotBlank()) { "Cookie 为空" }
        val host = resolveMaildomainHost(context, region)
        val data = requestJson(
            method = "GET",
            url = "https://$host/v2/hme/list",
            region = region,
            cookie = context.cookie,
        )
        ensureSuccess(data, "list emails")
        val emails = data.getJSONObject("result").optJSONArray("hmeEmails") ?: JSONArray()
        return buildList {
            for (index in 0 until emails.length()) {
                val item = emails.optJSONObject(index) ?: continue
                add(
                    HmeAddress(
                        email = item.optString("hme"),
                        label = item.optString("label"),
                        active = item.optBoolean("isActive"),
                        createdAt = item.optLong("createTimestamp"),
                    )
                )
            }
        }.filter { it.email.isNotBlank() }.sortedByDescending { it.createdAt }
    }

    private fun requestJson(
        method: String,
        url: String,
        region: ICloudRegion,
        cookie: String,
        payload: JSONObject? = null,
    ): JSONObject {
        val httpUrl = url.toHttpUrl().newBuilder()
            .addQueryParameter("clientBuildNumber", "2536Project32")
            .addQueryParameter("clientMasteringNumber", "2536B20")
            .addQueryParameter("clientId", "")
            .addQueryParameter("dsid", "")
            .build()

        val builder = baseRequest(httpUrl.toString(), cookie, region)
        if (method == "POST") {
            val body = (payload ?: JSONObject()).toString().toRequestBody("application/json".toMediaType())
            builder.post(body)
        } else {
            builder.get()
        }

        val response = client.newCall(builder.build()).execute()
        val body = response.body?.string().orEmpty()
        if (body.isBlank()) error("iCloud 返回空响应：${response.code}")
        return JSONObject(body)
    }

    private fun baseRequest(url: String, cookie: String, region: ICloudRegion): Request.Builder {
        return Request.Builder()
            .url(url)
            .header("Connection", "keep-alive")
            .header("Pragma", "no-cache")
            .header("Cache-Control", "no-cache")
            .header("User-Agent", "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/141.0.0.0 Mobile Safari/537.36")
            .header("Content-Type", "text/plain")
            .header("Accept", "*/*")
            .header("Origin", region.origin)
            .header("Referer", "${region.origin}/")
            .header("Accept-Language", "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7")
            .header("Cookie", cookie.trim())
    }

    private fun resolveMaildomainHost(context: CookieContext, region: ICloudRegion): String {
        return context.maildomainHost.ifBlank { region.defaultMaildomain }
    }

    private fun ensureSuccess(data: JSONObject, action: String) {
        if (data.optBoolean("success", false)) return
        val reason = when (val errorValue = data.opt("error")) {
            is JSONObject -> errorValue.optString("errorMessage", errorValue.toString())
            null -> data.optString("reason", data.toString())
            else -> data.optString("reason", errorValue.toString())
        }
        error("Failed to $action: $reason")
    }

    companion object {
        fun parseCookieContext(raw: String, region: ICloudRegion): CookieContext {
            val rawContent = raw.lineSequence()
                .map { it.trim() }
                .filter { it.isNotBlank() && !it.startsWith("//") }
                .joinToString("\n")
                .trim()
            val content = rawContent
                .replace("^\"", "\"")
                .replace("^'", "'")

            if (rawContent.isBlank()) return CookieContext("")

            val explicitHost = Regex("""(?m)^HIDEMYEMAIL_MAILDOMAIN_HOST=([A-Za-z0-9.-]+)\s*$""")
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
                .orEmpty()
                .trim()

            val base64Cookie = Regex("""(?m)^HIDEMYEMAIL_COOKIE_BASE64=([A-Za-z0-9+/=]+)\s*$""")
                .find(content)
                ?.groupValues
                ?.getOrNull(1)

            if (!base64Cookie.isNullOrBlank()) {
                val decoded = String(Base64.decode(base64Cookie, Base64.DEFAULT), Charsets.UTF_8)
                return CookieContext(decoded.trim(), explicitHost)
            }

            val shardHost = Regex("""https://(p\d+)-[^/\s'"]+\.icloud\.com(?:\.cn)?""")
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
                ?.let { "$it-maildomainws.icloud.${if (region == ICloudRegion.China) "com.cn" else "com"}" }
                .orEmpty()

            val maildomainHost = explicitHost.ifBlank { shardHost }

            val cmdCookieArg = Regex(
                """(?:^|\s)(?:-b|--cookie)\s+\^\"(.+?)\^\"\s+\^?\s*-[A-Za-z]""",
                setOf(RegexOption.IGNORE_CASE, RegexOption.DOT_MATCHES_ALL),
            ).find(rawContent)?.groupValues?.getOrNull(1)
            if (!cmdCookieArg.isNullOrBlank()) {
                val cookie = cmdCookieArg
                    .replace("^\\^\"", "\"")
                    .replace("\\\"", "\"")
                    .replace("^\"", "\"")
                    .replace("\r", "")
                    .replace("\n", "")
                    .trim()
                return CookieContext(cookie, maildomainHost)
            }

            val cookieFromDoubleQuote = Regex("""(?:^|\s)(?:-b|--cookie)\s+"([^"]+)"""", RegexOption.IGNORE_CASE)
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!cookieFromDoubleQuote.isNullOrBlank()) {
                return CookieContext(cookieFromDoubleQuote.trim(), maildomainHost)
            }

            val cookieFromSingleQuote = Regex("""(?:^|\s)(?:-b|--cookie)\s+'([^']+)'""", RegexOption.IGNORE_CASE)
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!cookieFromSingleQuote.isNullOrBlank()) {
                return CookieContext(cookieFromSingleQuote.trim(), maildomainHost)
            }

            val cookieHeader = Regex("""cookie\s*:\s*([^'"\r\n]+)""", RegexOption.IGNORE_CASE)
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!cookieHeader.isNullOrBlank()) {
                return CookieContext(cookieHeader.trim(), maildomainHost)
            }

            return CookieContext(content.lines().firstOrNull().orEmpty().trim(), maildomainHost)
        }

        fun detectRegion(raw: String): ICloudRegion? {
            val declaredRegion = Regex("""(?m)^HIDEMYEMAIL_REGION=(global|china)\s*$""", RegexOption.IGNORE_CASE)
                .find(raw)
                ?.groupValues
                ?.getOrNull(1)
                ?.lowercase(Locale.ROOT)
            if (declaredRegion != null) return ICloudRegion.from(declaredRegion)
            return if (raw.contains("icloud.com.cn", ignoreCase = true)) ICloudRegion.China else null
        }
    }
}

private fun Throwable.cleanMessage(): String {
    return message?.takeIf { it.isNotBlank() } ?: javaClass.simpleName
}

private fun Context.copyToClipboard(text: String) {
    val clipboard = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    clipboard.setPrimaryClip(ClipData.newPlainText("HideMyEmail", text))
}
