package com.hidemyemail.generator

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.util.Base64
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountCircle
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Email
import androidx.compose.material.icons.filled.Inbox
import androidx.compose.material.icons.filled.Language
import androidx.compose.material.icons.filled.OpenInBrowser
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Save
import androidx.compose.material.icons.filled.Settings
import androidx.compose.material.icons.filled.Verified
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.Divider
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Surface
import androidx.compose.material3.Tab
import androidx.compose.material3.TabRow
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import okhttp3.HttpUrl.Companion.toHttpUrl
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.concurrent.TimeUnit

private const val DEFAULT_NOTE = "Generated by HideMyEmail Android"
private const val LOCAL_STATE_UNUSED = "unused"
private const val LOCAL_STATE_USED = "used"
private const val LOCAL_STATE_TRASH = "trash"

object HmeEndpoints {
    const val generate = "/v1/hme/generate"
    const val reserve = "/v1/hme/reserve"
    const val list = "/v2/hme/list"
    const val updateMetadata = "/v1/hme/updateMetaData"
    const val deactivate = "/v1/hme/deactivate"
    const val reactivate = "/v1/hme/reactivate"
}

object HmeRequestDefaults {
    const val clientBuildNumber = "2626Build17"
    const val clientMasteringNumber = "2626Build17"
    const val userAgent =
        "Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Mobile Safari/537.36"
    const val secChUa = "\"Not;A=Brand\";v=\"8\", \"Chromium\";v=\"150\", \"Google Chrome\";v=\"150\""
}

enum class ICloudRegion(
    val id: String,
    val titleRes: Int,
    val origin: String,
    val defaultMaildomain: String,
    val generateLangCode: String,
) {
    Global(
        id = "global",
        titleRes = R.string.region_global,
        origin = "https://www.icloud.com",
        defaultMaildomain = "p68-maildomainws.icloud.com",
        generateLangCode = "en-us",
    ),
    China(
        id = "china",
        titleRes = R.string.region_china,
        origin = "https://www.icloud.com.cn",
        defaultMaildomain = "p217-maildomainws.icloud.com.cn",
        generateLangCode = "zh-cn",
    );

    companion object {
        fun from(value: String): ICloudRegion = values().firstOrNull { it.id == value } ?: Global
    }
}

data class CookieContext(
    val cookie: String,
    val maildomainHost: String = "",
)

data class AccountInfo(
    val appleId: String,
    val fullName: String,
    val dsid: String,
    val userPartition: String,
    val maildomainHost: String,
    val hideMyEmailAvailable: Boolean,
) {
    fun summary(context: Context): String {
        val unknown = context.getString(R.string.value_unknown)
        return listOf(
            context.getString(R.string.account_apple_id, appleId.ifBlank { unknown }),
            context.getString(R.string.account_name, fullName.ifBlank { unknown }),
            context.getString(R.string.account_dsid, dsid.ifBlank { unknown }),
            context.getString(R.string.account_partition, userPartition.ifBlank { unknown }),
            context.getString(R.string.account_maildomain, maildomainHost.ifBlank { unknown }),
            context.getString(
                R.string.account_hme,
                context.getString(if (hideMyEmailAvailable) R.string.value_available else R.string.value_unknown),
            ),
        ).joinToString("\n")
    }
}

data class HmeAddress(
    val anonymousId: String,
    val email: String,
    val label: String,
    val note: String,
    val active: Boolean,
    val createdAt: Long,
) {
    fun createdAtText(): String {
        if (createdAt <= 0) return ""
        return SimpleDateFormat("yyyy-MM-dd HH:mm", Locale.getDefault()).format(Date(createdAt))
    }
}

data class LocalAddress(
    val email: String,
    val label: String,
    val state: String,
    val updatedAt: Long,
)

data class GenerationResult(
    val addresses: List<HmeAddress>,
    val failure: Throwable? = null,
) {
    val retryAfterSeconds: Int?
        get() = (failure as? HmeRequestException)?.retryAfterSeconds
}

internal data class HmeHttpResponse(
    val code: Int,
    val body: String,
    val retryAfterSeconds: Int? = null,
) {
    val isSuccessful: Boolean
        get() = code in 200..299
}

internal fun interface HmeTransport {
    fun execute(request: Request): HmeHttpResponse
}

internal class HmeRequestException(
    message: String,
    val retryAfterSeconds: Int? = null,
) : IllegalStateException(message)

private class OkHttpHmeTransport : HmeTransport {
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS)
        .writeTimeout(30, TimeUnit.SECONDS)
        .build()

    override fun execute(request: Request): HmeHttpResponse {
        return client.newCall(request).execute().use { response ->
            HmeHttpResponse(
                code = response.code,
                body = response.body?.string().orEmpty(),
                retryAfterSeconds = response.header("Retry-After")?.toIntOrNull(),
            )
        }
    }
}

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            HideMyEmailTheme {
                HideMyEmailApp()
            }
        }
    }
}

@Composable
private fun HideMyEmailTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = lightColorScheme(
            primary = Color(0xFF116A7B),
            secondary = Color(0xFF8A5A12),
            tertiary = Color(0xFF6750A4),
            background = Color(0xFFF8FAFC),
            surface = Color.White,
            surfaceVariant = Color(0xFFE7EEF2),
            onPrimary = Color.White,
        ),
        content = content,
    )
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun HideMyEmailApp() {
    val context = LocalContext.current
    val store = remember { HmeStore(context) }
    val repository = remember { HmeRepository() }
    val scope = rememberCoroutineScope()
    val localAddresses = remember { mutableStateListOf<LocalAddress>() }
    val remoteAddresses = remember { mutableStateListOf<HmeAddress>() }
    val generatedAddresses = remember { mutableStateListOf<HmeAddress>() }

    var selectedTab by remember { mutableStateOf(0) }
    var region by remember { mutableStateOf(store.loadRegion()) }
    var cookieInput by remember { mutableStateOf(store.loadCookie()) }
    var maildomainHost by remember { mutableStateOf(store.loadMaildomainHost()) }
    var accountSummary by remember { mutableStateOf("") }
    var label by remember { mutableStateOf("generated") }
    var countText by remember { mutableStateOf("1") }
    var showActive by remember { mutableStateOf(true) }
    var managedAddress by remember { mutableStateOf<HmeAddress?>(null) }
    var busy by remember { mutableStateOf(false) }
    var message by remember { mutableStateOf(context.getString(R.string.status_ready)) }

    fun refreshLocal() {
        localAddresses.clear()
        localAddresses.addAll(store.loadLocalAddresses())
    }

    fun toLocalAddress(address: HmeAddress): LocalAddress {
        return LocalAddress(
            email = address.email,
            label = address.label,
            state = if (address.active) LOCAL_STATE_UNUSED else LOCAL_STATE_TRASH,
            updatedAt = System.currentTimeMillis(),
        )
    }

    fun applyRemoteAddresses(addresses: List<HmeAddress>) {
        remoteAddresses.clear()
        remoteAddresses.addAll(addresses)
        store.upsertLocalAddresses(addresses.map(::toLocalAddress))
        refreshLocal()
    }

    fun requestRegion(): ICloudRegion = HmeRepository.detectRegion(cookieInput) ?: region

    fun currentCookieContext(): CookieContext {
        val resolvedRegion = requestRegion()
        val parsed = HmeRepository.parseCookieContext(cookieInput, resolvedRegion)
        return if (maildomainHost.isNotBlank()) {
            parsed.copy(maildomainHost = HmeRepository.normalizeMaildomainHost(maildomainHost, resolvedRegion))
        } else {
            parsed
        }
    }

    fun saveSettings() {
        val detectedRegion = requestRegion()
        val parsed = HmeRepository.parseCookieContext(cookieInput, detectedRegion)
        val resolvedHost = if (maildomainHost.isNotBlank()) {
            HmeRepository.normalizeMaildomainHost(maildomainHost, detectedRegion)
        } else {
            parsed.maildomainHost
        }
        region = detectedRegion
        maildomainHost = resolvedHost
        store.saveSettings(detectedRegion, cookieInput, resolvedHost)
        message = context.getString(R.string.status_settings_saved)
    }

    suspend fun syncRemoteAddresses(resolvedRegion: ICloudRegion): Int {
        val addresses = withContext(Dispatchers.IO) {
            repository.listAddresses(currentCookieContext(), resolvedRegion)
        }
        applyRemoteAddresses(addresses)
        return addresses.size
    }

    fun performAddressAction(
        address: HmeAddress,
        progressRes: Int,
        successRes: Int,
        action: (CookieContext, ICloudRegion, HmeAddress) -> Unit,
    ) {
        saveSettings()
        val resolvedRegion = requestRegion()
        region = resolvedRegion
        scope.launch {
            busy = true
            message = context.getString(progressRes)
            val result = runCatching {
                withContext(Dispatchers.IO) {
                    action(currentCookieContext(), resolvedRegion, address)
                }
                syncRemoteAddresses(resolvedRegion)
            }
            result.onSuccess {
                managedAddress = null
                message = context.getString(successRes)
            }.onFailure {
                message = context.getString(R.string.operation_failed, it.cleanMessage())
            }
            busy = false
        }
    }

    LaunchedEffect(Unit) {
        refreshLocal()
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Column {
                        Text("HideMyEmail", fontWeight = FontWeight.SemiBold)
                        Text(
                            stringResource(R.string.app_subtitle),
                            style = MaterialTheme.typography.labelMedium,
                            color = MaterialTheme.colorScheme.secondary,
                        )
                    }
                },
            )
        },
    ) { padding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .background(MaterialTheme.colorScheme.background)
                .padding(padding),
        ) {
            val tabs = listOf(
                stringResource(R.string.tab_settings),
                stringResource(R.string.tab_generate),
                stringResource(R.string.tab_addresses),
                stringResource(R.string.tab_local),
            )
            TabRow(selectedTabIndex = selectedTab) {
                tabs.forEachIndexed { index, title ->
                    Tab(
                        selected = selectedTab == index,
                        onClick = { selectedTab = index },
                        text = { Text(title) },
                    )
                }
            }

            StatusBar(message = message, busy = busy)

            when (selectedTab) {
                0 -> SettingsScreen(
                    region = region,
                    onRegionChange = {
                        region = it
                        if (
                            maildomainHost == ICloudRegion.Global.defaultMaildomain ||
                            maildomainHost == ICloudRegion.China.defaultMaildomain
                        ) {
                            maildomainHost = ""
                        }
                    },
                    cookieInput = cookieInput,
                    onCookieChange = { cookieInput = it },
                    maildomainHost = maildomainHost,
                    onMaildomainChange = { maildomainHost = it },
                    accountSummary = accountSummary,
                    onSave = ::saveSettings,
                    onOpenICloud = {
                        context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse("${region.origin}/icloudplus/")))
                    },
                    onValidate = {
                        saveSettings()
                        val resolvedRegion = requestRegion()
                        region = resolvedRegion
                        scope.launch {
                            busy = true
                            message = context.getString(R.string.status_validating_cookie)
                            val result = runCatching {
                                withContext(Dispatchers.IO) {
                                    repository.fetchAccountInfo(currentCookieContext(), resolvedRegion)
                                }
                            }
                            result.onSuccess { account ->
                                accountSummary = account.summary(context)
                                maildomainHost = account.maildomainHost
                                store.saveSettings(resolvedRegion, cookieInput, maildomainHost)
                                message = context.getString(R.string.status_cookie_valid, account.appleId)
                            }.onFailure {
                                message = context.getString(R.string.operation_failed, it.cleanMessage())
                            }
                            busy = false
                        }
                    },
                )

                1 -> GenerateScreen(
                    label = label,
                    onLabelChange = { label = it },
                    countText = countText,
                    onCountChange = { countText = it.filter(Char::isDigit).take(2) },
                    generatedAddresses = generatedAddresses,
                    onGenerate = {
                        saveSettings()
                        val resolvedRegion = requestRegion()
                        region = resolvedRegion
                        val count = countText.toIntOrNull()?.coerceIn(1, 20) ?: 1
                        scope.launch {
                            busy = true
                            generatedAddresses.clear()
                            message = context.getString(R.string.status_generating, count)
                            val result = runCatching {
                                withContext(Dispatchers.IO) {
                                    repository.generate(
                                        context = currentCookieContext(),
                                        region = resolvedRegion,
                                        label = label.ifBlank { "generated" },
                                        count = count,
                                        onReserved = { address ->
                                            store.upsertLocalAddresses(listOf(toLocalAddress(address)))
                                        },
                                    )
                                }
                            }
                            result.onSuccess { generation ->
                                generatedAddresses.addAll(generation.addresses)
                                store.upsertLocalAddresses(generation.addresses.map(::toLocalAddress))
                                refreshLocal()
                                message = generationStatus(context, generation, count)
                            }.onFailure {
                                message = context.getString(R.string.operation_failed, it.cleanMessage())
                            }
                            busy = false
                        }
                    },
                )

                2 -> RemoteListScreen(
                    showActive = showActive,
                    onModeChange = { showActive = it },
                    addresses = remoteAddresses.filter { it.active == showActive },
                    onManage = { managedAddress = it },
                    onRefresh = {
                        saveSettings()
                        val resolvedRegion = requestRegion()
                        region = resolvedRegion
                        scope.launch {
                            busy = true
                            message = context.getString(R.string.status_loading_addresses)
                            val result = runCatching {
                                syncRemoteAddresses(resolvedRegion)
                            }
                            result.onSuccess { count ->
                                message = context.resources.getQuantityString(
                                    R.plurals.addresses_loaded,
                                    count,
                                    count,
                                )
                            }.onFailure {
                                message = context.getString(R.string.operation_failed, it.cleanMessage())
                            }
                            busy = false
                        }
                    },
                )

                3 -> LocalScreen(
                    addresses = localAddresses,
                    onMark = { email, state ->
                        store.markAddress(email, state)
                        refreshLocal()
                        message = context.getString(
                            R.string.status_address_marked,
                            email,
                            localStateTitle(context, state),
                        )
                    },
                    onClear = {
                        store.clearLocalAddresses()
                        refreshLocal()
                        message = context.getString(R.string.status_local_cleared)
                    },
                )
            }
        }
    }

    managedAddress?.let { address ->
        HmeAddressManagementDialog(
            address = address,
            onDismiss = { managedAddress = null },
            onSave = { newLabel, newNote ->
                performAddressAction(
                    address = address,
                    progressRes = R.string.status_updating_address,
                    successRes = R.string.status_address_updated,
                ) { cookieContext, resolvedRegion, item ->
                    repository.updateAddressMetadata(
                        context = cookieContext,
                        region = resolvedRegion,
                        anonymousId = item.anonymousId,
                        label = newLabel,
                        note = newNote,
                    )
                }
            },
            onChangeActivity = {
                if (address.active) {
                    performAddressAction(
                        address = address,
                        progressRes = R.string.status_deactivating_address,
                        successRes = R.string.status_address_deactivated,
                    ) { cookieContext, resolvedRegion, item ->
                        repository.deactivateAddress(cookieContext, resolvedRegion, item.anonymousId)
                    }
                } else {
                    performAddressAction(
                        address = address,
                        progressRes = R.string.status_reactivating_address,
                        successRes = R.string.status_address_reactivated,
                    ) { cookieContext, resolvedRegion, item ->
                        repository.reactivateAddress(cookieContext, resolvedRegion, item.anonymousId)
                    }
                }
            },
        )
    }
}

private fun generationStatus(context: Context, result: GenerationResult, requestedCount: Int): String {
    if (result.failure == null) {
        return context.resources.getQuantityString(
            R.plurals.addresses_generated,
            result.addresses.size,
            result.addresses.size,
        )
    }
    if (result.addresses.isEmpty()) {
        return context.getString(R.string.operation_failed, result.failure.cleanMessage())
    }
    val retryAfter = result.retryAfterSeconds
    return if (retryAfter == null) {
        context.getString(
            R.string.status_generation_partial,
            result.addresses.size,
            requestedCount,
            result.failure.cleanMessage(),
        )
    } else {
        context.getString(
            R.string.status_generation_partial_retry,
            result.addresses.size,
            requestedCount,
            retryAfter,
        )
    }
}

@Composable
private fun StatusBar(message: String, busy: Boolean) {
    Surface(
        tonalElevation = 1.dp,
        color = MaterialTheme.colorScheme.surface,
        modifier = Modifier.fillMaxWidth(),
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 10.dp),
            verticalAlignment = Alignment.CenterVertically,
            horizontalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            if (busy) {
                CircularProgressIndicator(modifier = Modifier.width(18.dp).height(18.dp), strokeWidth = 2.dp)
            } else {
                Icon(Icons.Default.Verified, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
            }
            Text(message, style = MaterialTheme.typography.bodyMedium, maxLines = 2, overflow = TextOverflow.Ellipsis)
        }
    }
}

@Composable
private fun SettingsScreen(
    region: ICloudRegion,
    onRegionChange: (ICloudRegion) -> Unit,
    cookieInput: String,
    onCookieChange: (String) -> Unit,
    maildomainHost: String,
    onMaildomainChange: (String) -> Unit,
    accountSummary: String,
    onSave: () -> Unit,
    onOpenICloud: () -> Unit,
    onValidate: () -> Unit,
) {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp),
    ) {
        SectionCard(title = stringResource(R.string.section_region), icon = Icons.Default.Language) {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                ICloudRegion.values().forEach { item ->
                    RegionButton(item, selected = region == item, onClick = { onRegionChange(item) })
                }
            }
        }

        SectionCard(title = stringResource(R.string.section_cookie), icon = Icons.Default.Settings) {
            OutlinedTextField(
                value = cookieInput,
                onValueChange = onCookieChange,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(190.dp),
                minLines = 5,
                label = { Text(stringResource(R.string.cookie_input_label)) },
            )
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(
                value = maildomainHost,
                onValueChange = onMaildomainChange,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                label = { Text(stringResource(R.string.maildomain_host_label)) },
                placeholder = { Text(region.defaultMaildomain) },
            )
            Spacer(Modifier.height(12.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                IconButtonText(stringResource(R.string.action_save), Icons.Default.Save, onSave)
                IconButtonText(stringResource(R.string.action_validate_account), Icons.Default.AccountCircle, onValidate)
                OutlinedIconButtonText(stringResource(R.string.action_open_icloud), Icons.Default.OpenInBrowser, onOpenICloud)
            }
        }

        if (accountSummary.isNotBlank()) {
            SectionCard(title = stringResource(R.string.section_current_account), icon = Icons.Default.AccountCircle) {
                Text(accountSummary, style = MaterialTheme.typography.bodyMedium)
            }
        }
    }
}

@Composable
private fun GenerateScreen(
    label: String,
    onLabelChange: (String) -> Unit,
    countText: String,
    onCountChange: (String) -> Unit,
    generatedAddresses: List<HmeAddress>,
    onGenerate: () -> Unit,
) {
    Column(
        modifier = Modifier
            .verticalScroll(rememberScrollState())
            .padding(16.dp),
        verticalArrangement = Arrangement.spacedBy(14.dp),
    ) {
        SectionCard(title = stringResource(R.string.section_generate), icon = Icons.Default.Add) {
            OutlinedTextField(
                value = label,
                onValueChange = onLabelChange,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                label = { Text(stringResource(R.string.label_input_label)) },
            )
            Spacer(Modifier.height(10.dp))
            OutlinedTextField(
                value = countText,
                onValueChange = onCountChange,
                modifier = Modifier.fillMaxWidth(),
                singleLine = true,
                label = { Text(stringResource(R.string.count_input_label)) },
                keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
            )
            Spacer(Modifier.height(12.dp))
            IconButtonText(stringResource(R.string.action_generate), Icons.Default.Add, onGenerate)
        }

        if (generatedAddresses.isNotEmpty()) {
            SectionCard(title = stringResource(R.string.section_generated_now), icon = Icons.Default.Email) {
                generatedAddresses.forEach { address ->
                    AddressRow(
                        email = address.email,
                        label = address.label,
                        meta = address.createdAtText(),
                        state = stringResource(if (address.active) R.string.state_active else R.string.state_inactive),
                    )
                }
            }
        }
    }
}

@Composable
private fun RemoteListScreen(
    showActive: Boolean,
    onModeChange: (Boolean) -> Unit,
    addresses: List<HmeAddress>,
    onManage: (HmeAddress) -> Unit,
    onRefresh: () -> Unit,
) {
    Column(modifier = Modifier.fillMaxSize()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            SectionCard(title = stringResource(R.string.section_icloud_addresses), icon = Icons.Default.Inbox) {
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    RegionButton(
                        stringResource(R.string.filter_active),
                        selected = showActive,
                        onClick = { onModeChange(true) },
                    )
                    RegionButton(
                        stringResource(R.string.filter_inactive),
                        selected = !showActive,
                        onClick = { onModeChange(false) },
                    )
                }
                Spacer(Modifier.height(12.dp))
                IconButtonText(stringResource(R.string.action_refresh), Icons.Default.Refresh, onRefresh)
            }
        }

        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            items(addresses, key = { it.email }) { item ->
                AddressCard(item, onManage)
            }
        }
    }
}

@Composable
private fun LocalScreen(
    addresses: List<LocalAddress>,
    onMark: (String, String) -> Unit,
    onClear: () -> Unit,
) {
    val unusedCount = addresses.count { it.state == LOCAL_STATE_UNUSED }
    val usedCount = addresses.count { it.state == LOCAL_STATE_USED }
    val trashCount = addresses.count { it.state == LOCAL_STATE_TRASH }
    Column(modifier = Modifier.fillMaxSize()) {
        Column(modifier = Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            SectionCard(title = stringResource(R.string.section_local_state), icon = Icons.Default.Inbox) {
                Text(stringResource(R.string.local_state_summary, unusedCount, usedCount, trashCount))
                Spacer(Modifier.height(10.dp))
                OutlinedIconButtonText(stringResource(R.string.action_clear_local), Icons.Default.Refresh, onClear)
            }
        }

        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 8.dp),
            verticalArrangement = Arrangement.spacedBy(10.dp),
        ) {
            items(addresses, key = { it.email }) { item ->
                LocalAddressCard(item, onMark)
            }
        }
    }
}

@Composable
private fun SectionCard(
    title: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    content: @Composable () -> Unit,
) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface),
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Row(verticalAlignment = Alignment.CenterVertically, horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                Icon(icon, contentDescription = null, tint = MaterialTheme.colorScheme.primary)
                Text(title, style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.SemiBold)
            }
            Spacer(Modifier.height(12.dp))
            content()
        }
    }
}

@Composable
private fun RegionButton(region: ICloudRegion, selected: Boolean, onClick: () -> Unit) {
    RegionButton(stringResource(region.titleRes), selected, onClick)
}

@Composable
private fun RegionButton(text: String, selected: Boolean, onClick: () -> Unit) {
    if (selected) {
        Button(onClick = onClick, shape = RoundedCornerShape(8.dp)) { Text(text) }
    } else {
        OutlinedButton(onClick = onClick, shape = RoundedCornerShape(8.dp)) { Text(text) }
    }
}

@Composable
private fun IconButtonText(
    text: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    onClick: () -> Unit,
) {
    Button(onClick = onClick, shape = RoundedCornerShape(8.dp)) {
        Icon(icon, contentDescription = null)
        Spacer(Modifier.width(8.dp))
        Text(text)
    }
}

@Composable
private fun OutlinedIconButtonText(
    text: String,
    icon: androidx.compose.ui.graphics.vector.ImageVector,
    onClick: () -> Unit,
) {
    OutlinedButton(onClick = onClick, shape = RoundedCornerShape(8.dp)) {
        Icon(icon, contentDescription = null)
        Spacer(Modifier.width(8.dp))
        Text(text)
    }
}

@Composable
private fun AddressCard(address: HmeAddress, onManage: (HmeAddress) -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
    ) {
        Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
            AddressRow(
                email = address.email,
                label = address.label,
                meta = address.createdAtText(),
                state = stringResource(if (address.active) R.string.state_active else R.string.state_inactive),
            )
            if (address.note.isNotBlank()) {
                Text(
                    stringResource(R.string.note_format, address.note),
                    modifier = Modifier.padding(horizontal = 14.dp),
                    style = MaterialTheme.typography.bodySmall,
                    color = Color(0xFF64748B),
                    maxLines = 2,
                    overflow = TextOverflow.Ellipsis,
                )
            }
            Divider()
            Row(
                modifier = Modifier.padding(horizontal = 14.dp, vertical = 6.dp),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
            ) {
                OutlinedButton(
                    onClick = { onManage(address) },
                    enabled = address.anonymousId.isNotBlank(),
                    shape = RoundedCornerShape(8.dp),
                ) {
                    Text(stringResource(R.string.action_manage))
                }
            }
        }
    }
}

@Composable
private fun HmeAddressManagementDialog(
    address: HmeAddress,
    onDismiss: () -> Unit,
    onSave: (String, String) -> Unit,
    onChangeActivity: () -> Unit,
) {
    var label by remember(address.anonymousId) { mutableStateOf(address.label) }
    var note by remember(address.anonymousId) { mutableStateOf(address.note) }
    var showDeactivateConfirmation by remember(address.anonymousId) { mutableStateOf(false) }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text(stringResource(R.string.dialog_manage_title)) },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Text(
                    address.email,
                    style = MaterialTheme.typography.bodyMedium,
                    fontWeight = FontWeight.SemiBold,
                )
                Text(
                    stringResource(if (address.active) R.string.state_active else R.string.state_inactive),
                    style = MaterialTheme.typography.bodySmall,
                    color = Color(0xFF64748B),
                )
                OutlinedTextField(
                    value = label,
                    onValueChange = { label = it },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true,
                    label = { Text(stringResource(R.string.label_input_label)) },
                )
                OutlinedTextField(
                    value = note,
                    onValueChange = { note = it },
                    modifier = Modifier.fillMaxWidth(),
                    minLines = 3,
                    label = { Text(stringResource(R.string.note_input_label)) },
                )
            }
        },
        confirmButton = {
            Button(
                onClick = { onSave(label.trim(), note.trim()) },
                enabled = label.trim().isNotBlank(),
            ) {
                Text(stringResource(R.string.action_save))
            }
        },
        dismissButton = {
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedButton(onClick = onDismiss) {
                    Text(stringResource(R.string.action_close))
                }
                OutlinedButton(
                    onClick = {
                        if (address.active) {
                            showDeactivateConfirmation = true
                        } else {
                            onChangeActivity()
                        }
                    },
                ) {
                    Text(stringResource(if (address.active) R.string.action_deactivate else R.string.action_reactivate))
                }
            }
        },
    )

    if (showDeactivateConfirmation) {
        AlertDialog(
            onDismissRequest = { showDeactivateConfirmation = false },
            title = { Text(stringResource(R.string.dialog_deactivate_title)) },
            text = { Text(stringResource(R.string.dialog_deactivate_message)) },
            confirmButton = {
                Button(
                    onClick = {
                        showDeactivateConfirmation = false
                        onChangeActivity()
                    },
                ) {
                    Text(stringResource(R.string.action_deactivate))
                }
            },
            dismissButton = {
                OutlinedButton(onClick = { showDeactivateConfirmation = false }) {
                    Text(stringResource(R.string.action_cancel))
                }
            },
        )
    }
}

@Composable
private fun AddressRow(email: String, label: String, meta: String, state: String) {
    val context = LocalContext.current
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(14.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.spacedBy(12.dp),
    ) {
        Column(modifier = Modifier.weight(1f)) {
            Text(email, fontWeight = FontWeight.SemiBold, maxLines = 1, overflow = TextOverflow.Ellipsis)
            Text(
                listOf(label, meta, state).filter { it.isNotBlank() }.joinToString(" | "),
                style = MaterialTheme.typography.bodySmall,
                color = Color(0xFF64748B),
                maxLines = 1,
                overflow = TextOverflow.Ellipsis,
            )
        }
        OutlinedButton(
            onClick = { context.copyToClipboard(email) },
            contentPadding = PaddingValues(horizontal = 12.dp, vertical = 8.dp),
            shape = RoundedCornerShape(8.dp),
        ) {
            Icon(Icons.Default.ContentCopy, contentDescription = null)
        }
    }
}

@Composable
private fun LocalAddressCard(address: LocalAddress, onMark: (String, String) -> Unit) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(8.dp),
        colors = CardDefaults.cardColors(containerColor = Color.White),
    ) {
        Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
            AddressRow(address.email, address.label, localStateTitle(LocalContext.current, address.state), "")
            Divider()
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                OutlinedButton(
                    onClick = { onMark(address.email, LOCAL_STATE_UNUSED) },
                    shape = RoundedCornerShape(8.dp),
                ) {
                    Text(stringResource(R.string.local_state_unused))
                }
                OutlinedButton(
                    onClick = { onMark(address.email, LOCAL_STATE_USED) },
                    shape = RoundedCornerShape(8.dp),
                ) {
                    Text(stringResource(R.string.local_state_used))
                }
                OutlinedButton(
                    onClick = { onMark(address.email, LOCAL_STATE_TRASH) },
                    shape = RoundedCornerShape(8.dp),
                ) {
                    Text(stringResource(R.string.local_state_trash))
                }
            }
        }
    }
}

private fun localStateTitle(context: Context, state: String): String {
    val resource = when (state) {
        LOCAL_STATE_UNUSED -> R.string.local_state_unused
        LOCAL_STATE_USED -> R.string.local_state_used
        LOCAL_STATE_TRASH -> R.string.local_state_trash
        else -> return state
    }
    return context.getString(resource)
}

class HmeStore(context: Context) {
    private val prefs = context.getSharedPreferences("hme-store", Context.MODE_PRIVATE)

    fun loadRegion(): ICloudRegion = ICloudRegion.from(prefs.getString("region", ICloudRegion.Global.id).orEmpty())

    fun loadCookie(): String = prefs.getString("cookie", "").orEmpty()

    fun loadMaildomainHost(): String = prefs.getString("maildomainHost", "").orEmpty()

    fun saveSettings(region: ICloudRegion, cookie: String, maildomainHost: String) {
        prefs.edit()
            .putString("region", region.id)
            .putString("cookie", cookie)
            .putString("maildomainHost", maildomainHost.trim())
            .apply()
    }

    fun loadLocalAddresses(): List<LocalAddress> {
        val raw = prefs.getString("localAddresses", "[]").orEmpty()
        val array = runCatching { JSONArray(raw) }.getOrElse { JSONArray() }
        return buildList {
            for (index in 0 until array.length()) {
                val item = array.optJSONObject(index) ?: continue
                add(
                    LocalAddress(
                        email = item.optString("email"),
                        label = item.optString("label"),
                        state = item.optString("state", LOCAL_STATE_UNUSED),
                        updatedAt = item.optLong("updatedAt"),
                    ),
                )
            }
        }.filter { it.email.isNotBlank() }.sortedByDescending { it.updatedAt }
    }

    fun upsertLocalAddresses(addresses: List<LocalAddress>) {
        val current = loadLocalAddresses().associateBy { it.email }.toMutableMap()
        addresses.forEach { address ->
            val existing = current[address.email]
            current[address.email] = address.copy(
                label = address.label.ifBlank { existing?.label.orEmpty() },
                state = if (existing?.state == LOCAL_STATE_USED) existing.state else address.state,
                updatedAt = System.currentTimeMillis(),
            )
        }
        saveLocalAddresses(current.values.sortedByDescending { it.updatedAt })
    }

    fun markAddress(email: String, state: String) {
        val current = loadLocalAddresses().map {
            if (it.email == email) it.copy(state = state, updatedAt = System.currentTimeMillis()) else it
        }
        saveLocalAddresses(current)
    }

    fun clearLocalAddresses() {
        prefs.edit().putString("localAddresses", "[]").apply()
    }

    private fun saveLocalAddresses(addresses: Collection<LocalAddress>) {
        val array = JSONArray()
        addresses.forEach { address ->
            array.put(
                JSONObject()
                    .put("email", address.email)
                    .put("label", address.label)
                    .put("state", address.state)
                    .put("updatedAt", address.updatedAt),
            )
        }
        prefs.edit().putString("localAddresses", array.toString()).apply()
    }
}

internal class HmeRepository(
    private val transport: HmeTransport = OkHttpHmeTransport(),
) {
    fun fetchAccountInfo(context: CookieContext, region: ICloudRegion): AccountInfo {
        require(context.cookie.isNotBlank()) { "Cookie is empty" }
        val url = when (region) {
            ICloudRegion.Global -> "https://setup.icloud.com/setup/ws/1/validate"
            ICloudRegion.China -> "https://setup.icloud.com.cn/setup/ws/1/validate"
        }
        val response = transport.execute(baseRequest(url, context.cookie, region).get().build())
        val data = parseResponse(response, "validate account")
        val dsInfo = data.optJSONObject("dsInfo") ?: JSONObject()
        val webservices = data.optJSONObject("webservices") ?: JSONObject()
        val maildomain = webservices.optJSONObject("maildomainws")
        val partition = data.optString("userPartition")
        val normalizedContextHost = normalizeMaildomainHost(context.maildomainHost, region)
        val detectedHost = normalizedContextHost.ifBlank {
            when {
                maildomain?.optString("url").orEmpty().isNotBlank() -> normalizeMaildomainHost(
                    Uri.parse(maildomain?.optString("url")).host.orEmpty(),
                    region,
                )
                partition.isNotBlank() -> "p$partition-maildomainws.icloud.${if (region == ICloudRegion.China) "com.cn" else "com"}"
                else -> region.defaultMaildomain
            }
        }
        val name = listOf(dsInfo.optString("firstName"), dsInfo.optString("lastName"))
            .filter { it.isNotBlank() }
            .joinToString(" ")
            .ifBlank { dsInfo.optString("fullName") }

        return AccountInfo(
            appleId = dsInfo.optString("appleId"),
            fullName = name,
            dsid = dsInfo.optString("dsid"),
            userPartition = partition,
            maildomainHost = detectedHost.ifBlank { region.defaultMaildomain },
            hideMyEmailAvailable = dsInfo.optBoolean("isHideMyEmailFeatureAvailable"),
        )
    }

    fun generate(
        context: CookieContext,
        region: ICloudRegion,
        label: String,
        count: Int,
        onReserved: (HmeAddress) -> Unit = {},
    ): GenerationResult {
        require(context.cookie.isNotBlank()) { "Cookie is empty" }
        require(count > 0) { "Count must be positive" }
        val host = resolveMaildomainHost(context, region)
        val out = mutableListOf<HmeAddress>()
        repeat(count) {
            try {
                val generated = requestJson(
                    method = "POST",
                    url = "https://$host${HmeEndpoints.generate}",
                    region = region,
                    cookie = context.cookie,
                    payload = JSONObject().put("langCode", region.generateLangCode),
                )
                val generatedData = ensureSuccess(generated, "generate email")
                val email = generatedData.getJSONObject("result").getString("hme")
                val reserved = requestJson(
                    method = "POST",
                    url = "https://$host${HmeEndpoints.reserve}",
                    region = region,
                    cookie = context.cookie,
                    payload = JSONObject()
                        .put("hme", email)
                        .put("label", label)
                        .put("note", DEFAULT_NOTE),
                )
                val reservedData = ensureSuccess(reserved, "reserve email")
                val address = HmeAddress(
                    anonymousId = reservedData.optJSONObject("result")?.optString("anonymousId").orEmpty(),
                    email = email,
                    label = label,
                    note = DEFAULT_NOTE,
                    active = true,
                    createdAt = System.currentTimeMillis(),
                )
                out += address
                onReserved(address)
            } catch (failure: Exception) {
                if (failure is CancellationException) throw failure
                return GenerationResult(out, failure)
            }
        }
        return GenerationResult(out)
    }

    fun listAddresses(context: CookieContext, region: ICloudRegion): List<HmeAddress> {
        require(context.cookie.isNotBlank()) { "Cookie is empty" }
        val data = requestJson(
            method = "GET",
            url = "https://${resolveMaildomainHost(context, region)}${HmeEndpoints.list}",
            region = region,
            cookie = context.cookie,
        )
        return parseHmeAddresses(ensureSuccess(data, "list emails"))
    }

    fun updateAddressMetadata(
        context: CookieContext,
        region: ICloudRegion,
        anonymousId: String,
        label: String,
        note: String,
    ) {
        require(context.cookie.isNotBlank()) { "Cookie is empty" }
        require(anonymousId.isNotBlank()) { "Missing iCloud address identifier" }
        val data = requestJson(
            method = "POST",
            url = "https://${resolveMaildomainHost(context, region)}${HmeEndpoints.updateMetadata}",
            region = region,
            cookie = context.cookie,
            payload = updateMetadataPayload(anonymousId, label, note),
        )
        ensureSuccess(data, "update email metadata")
    }

    fun deactivateAddress(context: CookieContext, region: ICloudRegion, anonymousId: String) {
        require(context.cookie.isNotBlank()) { "Cookie is empty" }
        require(anonymousId.isNotBlank()) { "Missing iCloud address identifier" }
        val data = requestJson(
            method = "POST",
            url = "https://${resolveMaildomainHost(context, region)}${HmeEndpoints.deactivate}",
            region = region,
            cookie = context.cookie,
            payload = anonymousIdPayload(anonymousId),
        )
        ensureSuccess(data, "deactivate email")
    }

    fun reactivateAddress(context: CookieContext, region: ICloudRegion, anonymousId: String) {
        require(context.cookie.isNotBlank()) { "Cookie is empty" }
        require(anonymousId.isNotBlank()) { "Missing iCloud address identifier" }
        val data = requestJson(
            method = "POST",
            url = "https://${resolveMaildomainHost(context, region)}${HmeEndpoints.reactivate}",
            region = region,
            cookie = context.cookie,
            payload = anonymousIdPayload(anonymousId),
        )
        ensureSuccess(data, "reactivate email")
    }

    private fun requestJson(
        method: String,
        url: String,
        region: ICloudRegion,
        cookie: String,
        payload: JSONObject? = null,
    ): HmeJsonResponse {
        val httpUrl = url.toHttpUrl().newBuilder()
            .addQueryParameter("clientBuildNumber", HmeRequestDefaults.clientBuildNumber)
            .addQueryParameter("clientMasteringNumber", HmeRequestDefaults.clientMasteringNumber)
            .addQueryParameter("clientId", "")
            .addQueryParameter("dsid", "")
            .build()
        val builder = baseRequest(httpUrl.toString(), cookie, region)
        if (method == "POST") {
            // text/plain matches the iCloud web client; OkHttp derives Content-Type from the body,
            // so setting it here rather than as a header is what actually reaches Apple.
            val body = (payload ?: JSONObject()).toString().toRequestBody("text/plain".toMediaType())
            builder.post(body)
        } else {
            builder.get()
        }
        val response = transport.execute(builder.build())
        return HmeJsonResponse(parseResponse(response, "perform request"), response.retryAfterSeconds)
    }

    private fun baseRequest(url: String, cookie: String, region: ICloudRegion): Request.Builder {
        return Request.Builder()
            .url(url)
            .header("Connection", "keep-alive")
            .header("Pragma", "no-cache")
            .header("Cache-Control", "no-cache")
            .header("User-Agent", HmeRequestDefaults.userAgent)
            .header("Content-Type", "text/plain")
            .header("Accept", "*/*")
            .header("Sec-GPC", "1")
            .header("Origin", region.origin)
            .header("Sec-Fetch-Site", "same-site")
            .header("Sec-Fetch-Mode", "cors")
            .header("Sec-Fetch-Dest", "empty")
            .header("Referer", "${region.origin}/")
            .header("Accept-Language", acceptLanguage(region))
            .header("sec-ch-ua", HmeRequestDefaults.secChUa)
            .header("sec-ch-ua-mobile", "?1")
            .header("sec-ch-ua-platform", "\"Android\"")
            .header("Cookie", cookie.trim())
    }

    private fun resolveMaildomainHost(context: CookieContext, region: ICloudRegion): String {
        return normalizeMaildomainHost(context.maildomainHost, region).ifBlank { region.defaultMaildomain }
    }

    private fun parseResponse(response: HmeHttpResponse, action: String): JSONObject {
        if (response.body.isBlank()) {
            throw HmeRequestException("iCloud returned an empty response (HTTP ${response.code})", response.retryAfterSeconds)
        }
        val data = try {
            JSONObject(response.body)
        } catch (_: Exception) {
            throw HmeRequestException("iCloud returned invalid JSON while attempting to $action", response.retryAfterSeconds)
        }
        if (!response.isSuccessful) {
            throw HmeRequestException(
                failureReason(data).ifBlank { "iCloud request failed (HTTP ${response.code})" },
                response.retryAfterSeconds,
            )
        }
        return data
    }

    private fun ensureSuccess(response: HmeJsonResponse, action: String): JSONObject {
        if (response.data.optBoolean("success", false)) return response.data
        throw HmeRequestException(
            "Failed to $action: ${failureReason(response.data)}",
            response.retryAfterSeconds,
        )
    }

    private fun failureReason(data: JSONObject): String {
        return when (val errorValue = data.opt("error")) {
            is JSONObject -> errorValue.optString("errorMessage", errorValue.toString())
            null -> data.optString("reason", data.toString())
            else -> data.optString("reason", errorValue.toString())
        }
    }

    private data class HmeJsonResponse(
        val data: JSONObject,
        val retryAfterSeconds: Int?,
    )

    companion object {
        fun parseHmeAddresses(data: JSONObject): List<HmeAddress> {
            val emails = data.optJSONObject("result")?.optJSONArray("hmeEmails") ?: JSONArray()
            return buildList {
                for (index in 0 until emails.length()) {
                    val item = emails.optJSONObject(index) ?: continue
                    add(
                        HmeAddress(
                            anonymousId = item.optString("anonymousId"),
                            email = item.optString("hme"),
                            label = item.optString("label"),
                            note = item.optString("note"),
                            active = item.optBoolean("isActive"),
                            createdAt = item.optLong("createTimestamp"),
                        ),
                    )
                }
            }.filter { it.email.isNotBlank() }.sortedByDescending { it.createdAt }
        }

        fun updateMetadataPayload(anonymousId: String, label: String, note: String): JSONObject {
            return JSONObject()
                .put("anonymousId", anonymousId)
                .put("label", label)
                .put("note", note)
        }

        fun anonymousIdPayload(anonymousId: String): JSONObject = JSONObject().put("anonymousId", anonymousId)

        fun acceptLanguage(region: ICloudRegion): String {
            return when (region) {
                ICloudRegion.Global -> "en-US,en;q=0.7"
                ICloudRegion.China -> "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7"
            }
        }

        fun parseCookieContext(raw: String, region: ICloudRegion): CookieContext {
            val rawContent = raw.lineSequence()
                .map { it.trim() }
                .filter { it.isNotBlank() && !it.startsWith("//") }
                .joinToString("\n")
                .trim()
            val content = rawContent
                .replace("^\\\"", "\"")
                .replace("^'", "'")
            if (rawContent.isBlank()) return CookieContext("")

            val resolvedRegion = detectRegion(content) ?: region
            val explicitHost = Regex("""(?m)^HIDEMYEMAIL_MAILDOMAIN_HOST=([A-Za-z0-9.-]+)\s*$""")
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
                .orEmpty()
                .trim()
                .let { normalizeMaildomainHost(it, resolvedRegion) }
            val base64Cookie = Regex("""(?m)^HIDEMYEMAIL_COOKIE_BASE64=([A-Za-z0-9+/=]+)\s*$""")
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!base64Cookie.isNullOrBlank()) {
                val decoded = runCatching {
                    String(Base64.decode(base64Cookie, Base64.DEFAULT), Charsets.UTF_8).trim()
                }.getOrDefault("")
                return CookieContext(decoded, explicitHost)
            }

            val shardHost = Regex("""https://(p\d+)-[^/\s'"]+\.icloud\.com(?:\.cn)?""")
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
                ?.let { "$it-maildomainws.icloud.${if (resolvedRegion == ICloudRegion.China) "com.cn" else "com"}" }
                .orEmpty()
            val maildomainHost = explicitHost.ifBlank { shardHost }

            val cmdCookieArg = Regex(
                """(?:^|\s)(?:-b|--cookie)\s+\^\"(.+?)\^\"\s+\^?\s*-[A-Za-z]""",
                setOf(RegexOption.IGNORE_CASE, RegexOption.DOT_MATCHES_ALL),
            ).find(rawContent)?.groupValues?.getOrNull(1)
            if (!cmdCookieArg.isNullOrBlank()) {
                val cookie = cmdCookieArg
                    .replace("^\\^\"", "\"")
                    .replace("\\\"", "\"")
                    .replace("^\"", "\"")
                    .replace("\r", "")
                    .replace("\n", "")
                    .trim()
                return CookieContext(cookie, maildomainHost)
            }

            val cookieFromDoubleQuote = Regex("""(?:^|\s)(?:-b|--cookie)\s+"([^"]+)"""", RegexOption.IGNORE_CASE)
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!cookieFromDoubleQuote.isNullOrBlank()) {
                return CookieContext(cookieFromDoubleQuote.trim(), maildomainHost)
            }

            val cookieFromSingleQuote = Regex("""(?:^|\s)(?:-b|--cookie)\s+'([^']+)'""", RegexOption.IGNORE_CASE)
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!cookieFromSingleQuote.isNullOrBlank()) {
                return CookieContext(cookieFromSingleQuote.trim(), maildomainHost)
            }

            val cookieHeader = Regex("""cookie\s*:\s*([^'"\r\n]+)""", RegexOption.IGNORE_CASE)
                .find(content)
                ?.groupValues
                ?.getOrNull(1)
            if (!cookieHeader.isNullOrBlank()) {
                return CookieContext(cookieHeader.trim(), maildomainHost)
            }

            val rawCookie = content.lines().firstOrNull().orEmpty().trim()
            if (Regex("""^[^=;\s]+=""").containsMatchIn(rawCookie)) {
                return CookieContext(rawCookie, maildomainHost)
            }
            return CookieContext("", maildomainHost)
        }

        fun normalizeMaildomainHost(host: String, region: ICloudRegion): String {
            val cleanHost = host
                .trim()
                .removePrefix("https://")
                .removePrefix("http://")
                .substringBefore('/')
            val shard = Regex("""^(p\d+)-maildomainws\.icloud\.com(?:\.cn)?$""")
                .matchEntire(cleanHost)
                ?.groupValues
                ?.getOrNull(1)
            return if (shard == null) {
                cleanHost
            } else {
                "$shard-maildomainws.icloud.${if (region == ICloudRegion.China) "com.cn" else "com"}"
            }
        }

        fun detectRegion(raw: String): ICloudRegion? {
            if (raw.contains("icloud.com.cn", ignoreCase = true)) return ICloudRegion.China
            val declaredRegion = Regex("""(?m)^HIDEMYEMAIL_REGION=(global|china)\s*$""", RegexOption.IGNORE_CASE)
                .find(raw)
                ?.groupValues
                ?.getOrNull(1)
                ?.lowercase(Locale.ROOT)
            return declaredRegion?.let(ICloudRegion::from)
        }
    }
}

private fun Throwable.cleanMessage(): String = message?.takeIf { it.isNotBlank() } ?: javaClass.simpleName

private fun Context.copyToClipboard(text: String) {
    val clipboard = getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
    clipboard.setPrimaryClip(ClipData.newPlainText("HideMyEmail", text))
}
